---
title: "patient-selection"
output: html_document
date: "2024-07-30"
---

```{r}
path <- "/Users/giac0002/Desktop/R/Biomarker2/Multiomics/preprocessing/"

patients_list <- read.csv("patients-selection.csv") 

all_unique_samples_collected_all_datasets <- rna_seq_metadata[, c("Record.ID", "Days")] %>% mutate(Dataset = "Transcriptomics", Lobe = NA) %>%
  full_join(bact_seq_metadata[, c("Record.ID", "Days", "Lobe")] %>% mutate(Dataset = "Bacteria")) %>%
  full_join(fungi_seq_metadata[, c("Record.ID", "Days", "Lobe")] %>% mutate(Dataset = "Fungi")) %>%
  full_join(met_sample_metadata[, c("Record.ID", "Days")] %>% mutate(Record.ID = as.numeric(as.character(Record.ID)), Dataset = "Small molecules", Lobe = NA )) %>%
  full_join(lip_sample_metadata[, c("Record.ID", "Days")] %>% mutate(Record.ID = as.numeric(as.character(Record.ID)), Dataset = "Small molecules", Lobe = NA )) %>% 
  distinct() %>%
  left_join(master_metadata$bal_class_hosp[, c("Record.ID", "Days", "BAL_class_combined")]) %>%
  left_join(clad_assessment[, c("Record.ID", "Transplanted")]) %>% # remove native lobes from bacterial dataset
  mutate(Lobe = case_when(Lobe == Transplanted ~ "transplanted",
                          Lobe != Transplanted ~ "native",
                          is.na(Lobe) ~ "transplanted")) %>%
  filter(Lobe == "transplanted") %>%
  dplyr::select(!c(Transplanted, Lobe) ) %>%
  filter(!c(Record.ID == 44 & Days == 182)) # remove sex mismatched sample

stable_patients <- patients_list %>% filter(Enrolled.in.stable.study == TRUE) %>% pull(Record.ID)
length(stable_patients) # 56
biomarker_patients <- patients_list %>% filter(Enrolled.in.biomarker.study == TRUE) %>% pull(Record.ID)
length(biomarker_patients) # 26

# biomarker
# CLAD free 
a %>% filter(Record.ID %in% c(1, 5, 6, 11, 13, 16, 19, 22, 23, 24, 29, 38, 44, 50, 52, 62)) %>% group_by(Record.ID) %>% slice_max(Days, n = 1)

# CLAD
a %>% filter(Record.ID %in% c(2, 8, 10, 21, 25, 57, 58, 61, 74, 75, 78, 81, 87)) %>% group_by(Record.ID) %>% slice_max(Days, n = 1)

# a %>% group_by(Record.ID) %>% dplyr::count() %>% arrange(n) %>% view()

fungi_seq_metadata %>% left_join(clad_assessment) %>% filter(clad_clinical == FALSE) %>% pull(Record.ID) %>% unique() %>% length()

length(unique(fungi_seq_metadata$Record.ID)) # 

saveRDS(all_unique_samples_collected_all_datasets, "all_unique_samples_collected_all_datasets.rds")
```

# Spirometry check

```{r}
# c <- c(1, 5, 6, 13, 16, 19, 24, 29, 38, 44, 52, 62, 68) # selected CLAD-free
# c <- c(2, 8, 10, 21, 25, 57, 58, 61, 74, 75, 78, 81, 87) # CLAD

c <- c(1, 5, 6, 9, 11, 12, 13, 16, 17, 19, 22, 23, 24, 26, 28, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 49, 50, 52, 54, 56, 62, 64, 66, 68, 69, 70, 71, 72, 73, 77, 80, 83, 84, 85, 88, 89, 91, 94, 106, 114, 116) # stable

for (i in c){

  d1 <- spirometry_metadata[, c("Record.ID", "Days", "Group", "FEV1_pre_percentage")] %>% filter(Record.ID == i, Days < 365*3) %>% arrange(Days)
  d2 <- all_unique_samples_collected_all_datasets[, c("Record.ID", "Days")] %>% distinct() %>% filter(Record.ID == i) %>% arrange(Days) #master_metadata$bronch_metadata
  d3 <- master_metadata$bal_class_hosp[, c("Record.ID", "Days", "BAL_class_combined", "BAL_class_separate", "Admission_indication", "Class_infection", "Class_inflammation")] %>% 
    filter(Record.ID == i, Days < 365*3) %>% 
    left_join(clad_assessment[, c("Record.ID", "Group", "clad_day_clinical")]) %>% arrange(Days)
  
  p <- 
    
    ggplot() +
      geom_path(data = d1, aes(x = Days, y = FEV1_pre_percentage), colour = "grey60", linewidth = 0.8) + # FEV path
      geom_point(data = d1, aes(x = Days, y = FEV1_pre_percentage), shape = 21) + # FEV

      geom_path(data = d2, aes(x = Days, y = max(d1$FEV1_pre_percentage)+5), colour = "grey60", linewidth = 0.8) + # bals path
      geom_point(data = d2, aes(x = Days, y = max(d1$FEV1_pre_percentage)+5), shape = 3, size = 1) + # bals

      geom_path(data = d3, aes(x = Days, y = max(d1$FEV1_pre_percentage)+2), colour = "grey60", linewidth = 0.8) + # clinical path
      geom_point(data = d3, aes(x = Days, y = max(d1$FEV1_pre_percentage)+2, fill = BAL_class_combined, shape = BAL_class_combined), size = 1.5) + # clinical episodes
      
      geom_vline(data = d3, aes(xintercept = clad_day_clinical), lty = "dashed") + # clad day
      geom_point(data = d3, aes(x = clad_day_clinical, y = max(d1$FEV1_pre_percentage)+2), shape = 4, colour = "red", size = 2) + #clad day
      
      labs(x = "Days post-transplant", 
           y = "FEV1% predicted",
           fill = "BAL class",
           shape = "BAL class",
           title = paste("Patient", i, "overview")) +
      theme +
      scale_shape_manual(values = c("Routine" = 21, "Clinical" = 24)) +
      scale_fill_manual(values = c("Routine" = "darkgrey", "Clinical" = "#FF6348"))
  
  ggsave(paste0("spirometry/stable-study/patient", i, "-fev.pdf"), p, width = 12, height = 7, units = 'cm')

}
```

```{r}
# c <- c(1, 5, 6, 13, 16, 19, 24, 29, 38, 44, 52, 62, 68) # selected CLAD-free
# c <- c(2, 8, 10, 21, 25, 57, 58, 61, 74, 75, 78, 81, 87) # CLAD

for (i in c){
  
d <- master_metadata$bronch_metadata %>%
  filter(Record.ID == i) %>% 
  mutate(Months = Days/30.417) %>%
  arrange(Record.ID, Days)
  
s <-
  
  spirometry_metadata %>% 
  filter(Record.ID == i) %>% 
  mutate(Months = Days/30.417) %>%
  arrange(Record.ID, Days) 
  
p <- 
    
  ggplot() +
  geom_path(aes(x = Days, y = lost, group = Record.ID), data = s) +
  geom_point(aes(x = Days, y = lost), data = s) +
  geom_point(aes(x = clad_day_clinical, y = 30), shape = 4, size = 3, colour = "red", data = s) +
  
  geom_point(aes(x = Days, y = 30), shape = 21, colour = "blue", data = d) +
  theme +
  labs(x = "Days post-transplant", 
       y = "FEV1% lost", 
       title = paste("Spirometry post-transplant patient", i),
       fill = "Group") +
  geom_vline(xintercept = 365, lty = "dashed") +
  geom_vline(xintercept = 730, lty = "dashed") +
  geom_hline(yintercept = 20, lty = "dashed")
  
ggsave(paste0("spirometry/all-patients-overview/patient", i, "-lost.pdf"), p, width = 12, height = 7, units = 'cm')

}
```

## Spirometry for each cohort

```{r}
d <- spirometry_metadata %>% 
  filter(Record.ID %in% c(stable_patients)) %>% 
  mutate(Record.ID = as.factor(as.character(Record.ID)),
         Months = round(Days/30.417, 1) ) %>% 
  filter(Months <= 30) %>%
  dplyr::select(Record.ID, FEV1_pre_percentage, Days, Months) %>% 
  arrange(Record.ID, Days)

#gam_mod <- gam(FEV1_pre_percentage ~ Record.ID + s(Days, by = Record.ID), data = d, method = "REML") 
#gam_df <- data.frame("Fitted" = round(fitted(gam_mod)) ) %>% 
#  mutate(FEV1_pre_percentage = d$FEV1_pre_percentage, Record.ID = d$Record.ID, Days = d$Days, Months = d$Months) %>% arrange(Record.ID, Days)

p <- ggplot(data = d, aes(x = Months, y = FEV1_pre_percentage)) +
  theme +
  labs(x = "Months post-transplant", 
       y = "FEV1% predicted", 
       title = "Stable cohort spirometry") +
  geom_smooth(aes(group = Record.ID), method = "lm", formula = y ~ ns(x, 3), se = FALSE, colour = "lightgrey", linewidth = 0.3) +
  geom_smooth(method = "lm", formula = y ~ ns(x, 3), colour = "#3a86ff", linewidth = 1 ) +
  scale_x_continuous(breaks = c(3, 6, 12, 18, 24, 30)) +
  #geom_vline(xintercept = 12, lty = "dashed") +
  scale_y_continuous(limits = c(0, 140))

ggsave("stable-patients-lmer-df3-30.pdf", p, width = 7, height = 7, units = 'cm')
ggsave("stable-patients-lmer-df3-30.png", p, width = 7, height = 7, units = 'cm', dpi = 500)
```

```{r}
d <- spirometry_metadata %>% 
  filter(Record.ID %in% c(biomarker_patients)) %>% 
  mutate(Record.ID = as.factor(as.character(Record.ID)),
         Months = round(Days/30.417, 1) ) %>% 
  filter(Months <= 30) %>%
  dplyr::select(Record.ID, FEV1_pre_percentage, Days, Months, clad_clinical) %>% 
  mutate(Group = as.factor(ifelse(clad_clinical == TRUE, "CLAD", "CLAD-free")) ) %>%
  arrange(Record.ID, Days)

p <- 
  
  ggplot(data = d, aes(x = Months, y = FEV1_pre_percentage)) +
  #geom_point(data = d_12, aes(fill = Group), shape = 21 ) +
  theme +
  labs(x = "Months post-transplant", 
       y = "FEV1% predicted", 
       title = "Biomarker cohort spirometry") +
  #geom_smooth(aes(group = Record.ID), method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, colour = "lightgrey", linewidth = 0.3) +
  #geom_smooth(aes(group = Group, colour = Group), method = "gam", formula = y ~ s(x, bs = "cs"), linewidth = 1 ) +
  
  geom_smooth(data = d, aes(group = Record.ID), method = "lm", formula = y ~ ns(x, 3), se = FALSE, colour = "lightgrey", linewidth = 0.3) +
  geom_smooth(data = d, aes(group = Group, colour = Group), method = "lm", formula = y ~ ns(x, 3), linewidth = 1 ) +
  scale_x_continuous(breaks = c(3, 6, 12, 18, 24, 30)) +
  #geom_vline(xintercept = 12, lty = "dashed") +
  plot_colours(Group = TRUE) +
  plot_fill(Group = TRUE) +
  scale_y_continuous(limits = c(0, 140))

ggsave("biomarker-patients-lmer-df3-30.pdf", p, width = 10, height = 7, units = 'cm')
ggsave("biomarker-patients-lmer-df3-30.png", p, width = 10, height = 7, units = 'cm', dpi = 500)

# Overall
m <- lmerTest::lmer(FEV1_pre_percentage ~ Group*Months + (1|Record.ID), data = d) 
summary(m)

m <- lm(FEV1_pre_percentage ~ Group, data = d_12) 
summary(m)
```

# Sample collection

```{r}
all_selected_samples_collected_across_datasets <- all_unique_samples_collected_all_datasets %>% 
  dplyr::select(!Dataset) %>%
  distinct() %>%
  left_join(patients_list[, c("Record.ID", "Enrolled.in.stable.study", "Enrolled.in.biomarker.study")]) %>%
  filter(Enrolled.in.stable.study == TRUE | Enrolled.in.biomarker.study == TRUE) %>%
  left_join(clad_assessment[, c("Record.ID", "clad_clinical", "clad_day_clinical")]) %>% 
  mutate(Patient_days = paste(Record.ID, Days, sep = "_"), 
         Group = ifelse(clad_clinical == TRUE, "CLAD", "CLAD-free"),
         Group = factor(Group, levels = c("CLAD-free", "CLAD")),
         Study = ifelse(Group == "CLAD-free" & Enrolled.in.stable.study == TRUE & Enrolled.in.biomarker.study == TRUE, "Stable &\nBiomarker",
                        ifelse(Group == "CLAD-free" & Enrolled.in.stable.study == TRUE & Enrolled.in.biomarker.study == FALSE, "Stable",
                               ifelse(Group == "CLAD" & Enrolled.in.biomarker.study == TRUE, "Biomarker", NA))),
         Study = factor(Study, levels = c("Stable", "Stable &\nBiomarker", "Biomarker")),
         CLAD_diagnosis = "CLAD diagnosis", 
         Months = round(Days/30.417, 1),
         days_to_clad = clad_day_clinical - Days) %>%
  filter(is.na(days_to_clad) | days_to_clad >= -30, Months < 26)

p <- 
  
  ggplot() +
  geom_path(data = all_selected_samples_collected_across_datasets, aes(x = Months, y = as.character(Record.ID), group = Record.ID), colour = "grey60", linewidth = 0.8) + # connect bals
  geom_point(data = all_selected_samples_collected_across_datasets, aes(x = Months, y = as.character(Record.ID), group = Record.ID), shape = 21) + # bals
  
  geom_point(data = all_selected_samples_collected_across_datasets %>% filter(Group == "CLAD"), aes(x = round(clad_day_clinical/30.417, 1), y = as.character(Record.ID), colour = CLAD_diagnosis), shape = 4,  size = 1) + #clad day
  labs(x = "Months post-transplant", 
       y = "Patient",
       colour = "",
       title = "Sample collection") +
  theme +
  theme(axis.text.y = element_blank(),
        legend.position = "bottom", legend.justification = "right") +
  facet_grid(Group+Study~., scales = "free", space = "free", switch = "y") +
  scale_x_continuous(breaks = c(0, 2, 6, 12, 18, 24, 30)) +
  scale_colour_manual(values = c("CLAD diagnosis" = "red"))

ggsave("sample-collection.pdf", p, width = 9, height = 18, units = 'cm')
```

## Sample overlap across datasets

```{r}
all_selected_samples_collected_all_datasets <- all_unique_samples_collected_all_datasets %>%
  left_join(patients_list[, c("Record.ID", "Enrolled.in.stable.study", "Enrolled.in.biomarker.study", "CLAD")]) %>%
  filter(Enrolled.in.stable.study == TRUE | Enrolled.in.biomarker.study == TRUE) %>%
  mutate(Patient_days = paste(Record.ID, Days, sep = "_"), 
         Months = round(Days/30.417, 1),
         Group = ifelse(CLAD == TRUE, "CLAD", "CLAD-free"),
         Group = factor(Group, levels = c("CLAD-free", "CLAD")),
         Study = ifelse(Group == "CLAD-free" & Enrolled.in.stable.study == TRUE & Enrolled.in.biomarker.study == TRUE, "Stable &\nBiomarker",
                        ifelse(Group == "CLAD-free" & Enrolled.in.stable.study == TRUE & Enrolled.in.biomarker.study == FALSE, "Stable",
                               ifelse(Group == "CLAD" & Enrolled.in.biomarker.study == TRUE, "Biomarker", NA))),
         Study = factor(Study, levels = c("Stable", "Stable &\nBiomarker", "Biomarker")) ) %>%
  filter(Patient_days %in% all_selected_samples_collected_across_datasets$Patient_days)
length(unique(all_selected_samples_collected_all_datasets$Patient_days)) # 408

# ALL
all_unique_samples_collected_all_datasets %>% group_by(Dataset) %>% dplyr::count()

p <- 
  
  ggplot(data = all_unique_samples_collected_all_datasets, aes(x = Days, y = Dataset)) +
  geom_tile(aes(fill = Dataset), size = 6) +
  theme +
  theme(axis.text.y = element_blank(),
        legend.position = "bottom", 
        strip.text = element_text(size = 8) ) + #strip.text = element_text(size = 8, margin = margin(t = 0, r = 0.1, b = 0, l = 0.1, unit = "cm"))
  labs(x = "Days post-transplant", y = "Dataset", title = "Omics datasets") +
  #facet_grid(Group+Study~., scales = "free", space = "free", switch = "y") +
  #scale_x_continuous(expand = c(0, 0), breaks = c(0, 2, 6, 12, 18, 24, 30)) +
  scale_fill_manual(values = c("Transcriptomics" = "#ec0868", "Small molecules" = "#7014f2", "Fungi" = "#353535", "Bacteria" = "#008bf8"))

ggsave("omics-datasets-days.pdf", p, width = 15, height = 10, units = 'cm')
```


```{r}
l <- list("Bacteria" = unique(bact_seq_metadata$Patient_days),
          #"Fungi" = unique(fungi_seq_metadata$Patient_days),
          "RNA" = unique(rna_seq_metadata$Patient_days),
          "Molecules" = unique(met_sample_metadata$Patient_days))

p <- 
ggVennDiagram(l, label_alpha = 0, label_size = 6, label = "count") + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "none") +
  labs(title = "Overlapping samples") +
  scale_fill_gradient(low = "white", high = "lightgrey") +
  scale_x_continuous(expand = expansion(mult = .2))
ggsave("overlapping-no-its.pdf", p, width = 15, height = 10, units = 'cm')
```


```{r}
l <- list("Bacteria" = unique(bact_seq_metadata$Record.ID),
          #"Fungi" = unique(fungi_seq_metadata$Record.ID),
          "RNA" = unique(rna_seq_metadata$Record.ID),
          "Molecules" = unique(met_sample_metadata$Record.ID))

p <- 
ggVennDiagram(l, label_alpha = 0, label_size = 6, label = "count") + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "none") +
  labs(title = "patients") +
  scale_fill_gradient(low = "white", high = "lightgrey") +
  scale_x_continuous(expand = expansion(mult = .2))
ggsave("overlapping-patients-no-its.pdf", p, width = 15, height = 10, units = 'cm')

l_p <- process_region_data(Venn(l))$item 
names(l_p) <- process_region_data(Venn(l))$name

l_p$`Bacteria/RNA` # 3 CLAD patients not in the metabs dataset
```

# Clinical investigation

```{r}
# Sample list
all_unique_samples_collected_all_datasets %>% 
  left_join(master_metadata$general_metadata[, c("Record.ID", "ParticipantInitials")]) %>%
  dplyr::select(Record.ID, ParticipantInitials, Days, Dataset) %>% 
  distinct() %>%
  arrange(Record.ID, Days) %>%
  write.csv(., "clinical-investigation/sample-list.csv", row.names = FALSE)

# Patient list
all_unique_samples_collected_all_datasets %>% 
  left_join(master_metadata$general_metadata[, c("Record.ID", "ParticipantInitials")]) %>%
  dplyr::select(Record.ID, ParticipantInitials, Dataset) %>% 
  distinct() %>%
  arrange(Record.ID) %>%
  write.csv(., "clinical-investigation/patient-list.csv", row.names = FALSE)
```



