---
title: "Biomarker cohort - Transcriptomics associations post-transplant"
author: "Giulia Iacono"
output: html_document
date: Sys.Date()
---

# Biomarker cohort - Transcriptomics associations post-transplant

```{r}
biomarker_rna_metadata <- rna_corrected$samples %>% filter(Record.ID %in% biomarker_patients)
biomarker_rna <- rna_corrected$counts[, biomarker_rna_metadata$Patient_days]
identical(biomarker_rna_metadata$Patient_days, colnames(biomarker_rna)) #TRUE
dim(biomarker_rna) # 12707 127
biomarker_rna_metadata %>% group_by(Record.ID) %>% dplyr::count() # 26
```

# *DESEQ2 Differential expression group + months

```{r}
# deseq_list$`group+months` <- NULL
test_variable <- "group+months"

m <- biomarker_rna_metadata %>% filter(!is.na(GIT_ischemic_time))
d <- biomarker_rna[, m$Patient_days]

de_matrix <- model.matrix(~Group + ns(Months, df = 3) + Transplant_indication + Total_ant_num + GIT_ischemic_time, m) 
deseq_list[[test_variable]][["design"]] <- "Group + ns(Months, df = 3) + Transplant_indication + Total_ant_num + GIT_ischemic_time"

# view(bind_rows(deseq_list$`group+months`$de_summary)) 
deseq_list$`group+months`$GroupCLAD$res_df %>% view()
```

```{r}
# Run
dds <- DESeqDataSetFromMatrix(countData = d,
                              colData = m,
                              design = de_matrix)  
dds <- DESeq(dds, minReplicatesForReplace = 3) 
mcols(dds)$maxCooks <- apply(assays(dds)[["cooks"]], 1, max) # add max cooks column
deseq_list[[test_variable]][["dds"]] <- dds

vsd <- vst(dds, blind=FALSE) 
deseq_list[[test_variable]][["vsd"]] <- vsd

# resultsNames(dds)

for (i in c(2)){ 
  
  name <- resultsNames(dds)[i]
  res <- lfcShrink(dds, coef = name, lfcThreshold = 0, type = "ashr", parallel = TRUE, BPPARAM = SnowParam(6) )
  deseq_list[[test_variable]][[name]][["res"]] <- res
  
  logFC_threshold <- 0
  
  c <- data.frame("maxCooks" = mcols(dds)$maxCooks, "Gene" = names(mcols(dds)$maxCooks))
    
  res.df <- as.data.frame(res) %>% 
    rownames_to_column("Gene") %>%
    left_join(c) %>%
    mutate(Direction = case_when(
        padj < 0.05 & log2FoldChange <= -logFC_threshold ~ "Decreased",
        padj < 0.05 & log2FoldChange >= logFC_threshold ~ "Increased",
        padj >= 0.05 | abs(log2FoldChange) < logFC_threshold ~ 'n.s.',
        is.na(padj) == TRUE | is.na(pvalue) == TRUE ~ "NA")) 
  deseq_list[[test_variable]][[name]][["res_df"]] <- res.df
  
  sig.results.df <- res.df %>% filter(padj < 0.05 & abs(log2FoldChange) >= logFC_threshold)  
  deseq_list[[test_variable]][[name]][["sig_results_df"]] <- sig.results.df
  deseq_list[[test_variable]][[name]][["heat_sig"]] <- t(scale(t(as.data.frame( assay(vsd)[rownames(assay(vsd)) %in% sig.results.df$Gene,]))))
  
  if (nrow(sig.results.df) == 0){
    next 
  }

  g <- sig.results.df %>% group_by(Direction) %>% mutate(Genes = paste0(Gene, collapse = ", ")) %>% dplyr::select(Direction, Genes) %>% distinct()
  
  deseq_list[[test_variable]][["de_summary"]][[name]] <- sig.results.df %>% 
    group_by(Direction) %>% 
    dplyr::count() %>% 
    ungroup() %>%    
    left_join(g, by = "Direction") %>%
    mutate(Name = name) 
  
  top.results.df <- res.df %>% filter(padj < 0.01 & abs(log2FoldChange) >= logFC_threshold) 
  deseq_list[[test_variable]][[name]][["top_results_df"]] <- top.results.df
   if (nrow(top.results.df) > 0){
      deseq_list[[test_variable]][[name]][["heat_top"]] <- t(scale(t(as.data.frame( assay(vsd)[rownames(assay(vsd)) %in% top.results.df$Gene,] )))) 
    }
}

saveRDS(deseq_list, "biomarker-rna-associations/deseq_list.rds")
#deseq_list <- readRDS("biomarker-rna-associations/deseq_list.rds")
```

```{r}
biomarker_rna_combined_df <- deseq_list$`group+months`$GroupCLAD$sig_results_df %>%
  filter(abs(log2FoldChange) >= 1) 
biomarker_rna_combined <- biomarker_rna_combined_df$Gene
length(biomarker_rna_combined) # 222
```


## Export gene list

```{r}
dset <- biomarker_rna_combined_df 
gene.list <- list()
d <- read.csv("genes-database/genes-database.csv") 

for (i in 1:length(dset$Gene)){
  gene <- geneinfo_2_html(dset$Gene[i])
  gene <- sub(".*GeneCards database: <a href = ", "", gene)
  gene <- sub(" target.*", "", gene)
  gene <- gsub('"', '', gene)
  gene.list[[i]] <- gene
}
g <- dplyr::bind_cols(gene.list) %>% t() %>% as.data.frame %>% remove_rownames()
gene_links <- data.frame("Link" = g$V1, 
                         "Gene" = dset$Gene) %>% 
  left_join(d) %>% 
  right_join(biomarker_rna_combined_df) %>%
  arrange(Gene)
write.csv(gene_links, "deseq/group+months/gene-links.csv", row.names = FALSE)

# rm(gene.list, gene, dset, d, g)
```

## Heatmap with intervals

```{r}
rna_combined_heat <- as.data.frame(deseq_list$`group+months`$GroupCLAD$heat_sig) 

gene_cluster_assignment_filt <- deseq_list$`group+months`$GroupCLAD$sig_results_df %>% 
  filter(Gene %in% biomarker_rna_combined) %>%
  as.data.frame() %>%
  mutate(Direction = factor(Direction))
rownames(gene_cluster_assignment_filt) <- gene_cluster_assignment_filt$Gene

m <- read.csv("biomarker-rna-heatmap.csv") %>%
  mutate(Direction = factor(Direction, levels = c("Increased", "Decreased"))) %>%
  arrange(Direction, Pathway)

rna_combined_heat_intervals <- rna_combined_heat %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  left_join(biomarker_rna_metadata[, c("Patient_days", "Months_grouped", "Group")]) %>%
  dplyr::select(!c("Patient_days")) %>%
  group_by(Group, Months_grouped) %>%
  summarise(across(where(is.numeric), mean)) %>%
  ungroup() %>%
  mutate(Group_month = paste(Group, Months_grouped, sep = "_")) %>%
  dplyr::select(!c("Group", "Months_grouped")) %>%
  column_to_rownames("Group_month") %>%
  t() %>%
  as.data.frame()

rna_combined_heat_intervals <- rna_combined_heat_intervals[m$Gene, ] 

df <- biomarker_rna_metadata[, c("Months_grouped", "Immunosuppression", "Group")] %>% 
  distinct() %>% 
  arrange(Group, Months_grouped) %>%
  mutate(Group_month = paste(Group, Months_grouped, sep = "_"),
         Group_month = factor(Group_month, levels = unique(Group_month))) %>%
  rename(`Time post-transplant (months)` = Months_grouped)
rownames(df) <- df$Group_month

identical(rownames(rna_combined_heat_intervals), m$Gene) # TRUE
identical(colnames(rna_combined_heat_intervals), rownames(df))

colHm <- colorRamp2(breaks = seq(-2, 2, length = 7), colors=c('#2166ac','#67a9cf','#d1e5f0', '#f7f7f7', '#fddbc7', '#ef8a62', '#CD0514'))
```

```{r}
# Annotation
text_list_big <- read.csv("deseq/group+months/biomarker-rna-heatmap.csv") %>% filter(sc_heatmap_annotation == TRUE) %>% pull(Gene)

row_position <- rna_combined_heat_intervals %>% 
  rownames_to_column("Genes") %>% 
  mutate(Row = c(1:nrow(.))) %>% 
  dplyr::select(Genes, Row)

row_position_big <- row_position %>%
  filter(Genes %in% text_list_big)

text_annotation_big <- anno_mark(at = row_position_big %>% pull(Row) %>% as.numeric(), 
                                                   labels = row_position_big %>% pull(Genes), 
                                                   labels_gp = gpar(fontsize = 12, fontface = "bold"),
                                 which = "row")

text_annotation <- rowAnnotation(#text_annotation_small = text_annotation_small,
                                 text_annotation_big = text_annotation_big)
```

```{r, fig.height=8, fig.width=10}
p <- 
  
  draw(Heatmap(as.matrix(rna_combined_heat_intervals), 
        col = colHm,
        name = "z-score",
        column_title = "DE genes",
        column_title_gp = gpar(fontface = "bold"),
        row_title_gp = gpar(fontface = "bold"),
        row_names_gp = gpar(fontsize = 8),
        show_column_names = FALSE,
        show_row_names = TRUE,
        show_parent_dend_line = FALSE,
        cluster_row_slices = TRUE,
        cluster_rows = TRUE,
        show_row_dend = FALSE,
        top_annotation = annotate_heatmap(df, c("Immunosuppression", "Time post-transplant (months)", "Group")),
        column_order = levels(df$Group_month),
        row_split = m %>% pull(Direction) ),
     padding = unit(c(0, 0, 0, 0), "cm"),
     merge_legend = TRUE,
     heatmap_legend_side = "left")

png(paste0(analysis_path, "transcriptomics-small-molecules/deseq/group+months/heat-cluster-direction-text.png"), width = 18, height = 25, units = "cm", res = 600)
p
invisible(dev.off())
```

```{r}
p2 <- 
  
  m %>% 
  arrange(desc(Direction), Pathway) %>% 
  mutate(Gene = factor(Gene, levels = unique(Gene))) %>%
  
  ggplot(aes(axis1 = Gene, axis2 = Pathway)) +
  scale_x_discrete(expand = c(.05, .05)) + 
  geom_alluvium(aes(fill = Pathway), fill = "grey60") +
  geom_stratum(size = 0.1, width = 0.2, alpha = 0.3) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 2) +
  theme_void() +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_blank())

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/deseq/group+months/alluvium-text.png"), p2, width = 4, height = 20, units = "cm", dpi = 600)
```

```{r}
# Each individual patient
b <- biomarker_rna_metadata[, c("Record.ID", "Group", "Months", "Patient_days")] %>% mutate(Record.ID = as.factor(Record.ID)) %>% arrange(Group, Record.ID, Months)
m <- rna_combined_heat %>% dplyr::select(b$Patient_days)

p <- 
  
  draw(Heatmap(as.matrix(m), 
        col = colHm,
        name = "z-score",
        column_title = "DE genes",
        column_title_gp = gpar(fontface = "bold"),
        row_title_gp = gpar(fontface = "bold"),
        show_column_names = FALSE,
        show_row_names = FALSE,
        show_parent_dend_line = FALSE,
        cluster_row_slices = FALSE,
        cluster_rows = TRUE,
        show_row_dend = FALSE,
        top_annotation = annotate_heatmap(b, c("Record.ID", "Group")),
        column_order = b$Patient_days
        ),
     padding = unit(c(0, 0, 0, 0), "cm"),
     merge_legend = TRUE,
     heatmap_legend_side = "left")

png("deseq/group+months/biomarker-heat-interval-all.png", width = 18, height = 25, units = "cm", res = 500)
p
invisible(dev.off())
```


## Pathways

```{r}
# deseq_list$`group+months`$cluster_genes <- NULL
  #d <- b_cluster_rna_df %>% filter(Direction_cluster == unique(b_cluster_rna_df$Direction_cluster)[i]) %>% pull(Gene)
  
  gene.df <- rna_corrected$genes %>% filter(SYMBOL %in% biomarker_rna_combined) 

  ego <- enrichGO(gene = gene.df$ENTREZID,
                  OrgDb         = org.Hs.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.2,
                  qvalueCutoff  = 0.2,
                  readable = TRUE)
  ego@result$log_adjpvalue <- abs(log10(ego@result$p.adjust))
  if (nrow(ego@result) > 0){
    if (length(unique(ego@result$geneID)) < nrow(ego@result)){
      ego@result <- aggregate(ego@result, by = list(ego@result$geneID), FUN = function(x) {
                                                                    if (is.numeric(x))
                                                                      cbind(x[1]) #max(x)
                                                                    else if (is.character(x))
                                                                      cbind(x[1])
                                                                    }) # keep first value only
    }
  }
  deseq_list$`group+months`[["cluster_genes"]][["ego"]] <- ego
  
  ego@result$qvalue <- NA
  ego.simp <- clusterProfiler::simplify(ego, cutoff = 0.35, by="p.adjust")
  deseq_list$`group+months`[["cluster_genes"]][["ego_simp"]] <- ego.simp

# rm(ego, ego.simp, gene.df)

deseq_list$`group+months`$cluster_genes$ego_simp@result %>% arrange(p.adjust) %>% filter(p.adjust < 0.05, Count >= 6) 
```

```{r}
biomarker_rna_pathways <- deseq_list$`group+months`$cluster_genes$ego_simp@result %>% 
  arrange(p.adjust) %>% 
  filter(p.adjust < 0.05, Count > 7) %>%
  mutate(Description = str_to_sentence(Description),
         Description = gsub("dna-binding", "DNA-binding", Description))

p <- 
  
ggplot(biomarker_rna_pathways, aes(x = 1, y = reorder(Description, -log(p.adjust)))) +
  geom_point(aes(fill = -log(p.adjust), size = Count), shape = 21) +
  theme +
  theme(legend.position = "right", legend.justification = "left", legend.box = "vertical", legend.title = element_text(face = "bold")) +
    theme(axis.text.x = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_line(size = 0)
        ) +
  labs(title = paste("Pathways"),
       x = " ",
       y = " ",
       fill = "-Log(p-adj)",
       size = "DE genes") +
  scale_fill_gradient(low = "#150578", high = "#f78436") 

ggsave("deseq/group+months/biomarker-pathways.pdf", p, width = 13, height = 9, units = 'cm')  
ggsave("deseq/group+months/biomarker-pathways.png", p, width = 13, height = 9, units = 'cm', dpi = 500)  
```

# TMixClust cluster DE genes in CLAD group 

```{r}
m <- biomarker_rna_metadata %>% filter(!is.na(GIT_ischemic_time), Group == "CLAD")
g <- biomarker_rna_combined_df %>% filter(Direction == "Increased") %>% pull(Gene)

d <- as.data.frame(deseq_list$`group+months`$GroupCLAD$heat_sig)[g, m$Patient_days]

data <- d %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  left_join(m[, c("Patient_days", "Months_grouped")]) %>%
  dplyr::select(!c("Patient_days")) %>%
  group_by(Months_grouped) %>%
  summarise(across(where(is.numeric), mean)) %>%
  column_to_rownames("Months_grouped") %>%
  t() %>%
  as.data.frame() 
saveRDS(data, paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/biomarker/data.rds"))

dim(data) #220 7

cluster_obj <- list()
for (i in 2:3){
  n_clust <- i
  cluster_obj[[n_clust]] <- TMixClust(data, nb_clusters = n_clust)
}
saveRDS(cluster_obj, paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/biomarker/cluster_obj.rds") )
#cluster_obj <- readRDS(paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/cluster_obj_interval.rds")

plot_silhouette(cluster_obj[[3]]) # 2 0.26 - 3 0.17 - 4 0.19

# plot the time series in each cluster
for (i in 1:3) {
plot_time_series_df(data[which(cluster_obj[[3]]$em_cluster_assignment == i), ], plot_title = paste("cluster",i))
}

b_cluster_genes <- list()
for (i in 1:3) {
b_cluster_genes[[i]] <- rownames(data[which(cluster_obj[[3]]$em_cluster_assignment == i), ]) 
}
saveRDS(b_cluster_genes, paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/biomarker/b_cluster_genes.rds"))
#b_cluster_genes <- readRDS(paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/b_cluster_genes.rds")

length(unique(unlist(b_cluster_genes))) # 220

length(b_cluster_genes[[1]]) # 56 down up
length(b_cluster_genes[[2]]) # 103 down up
length(b_cluster_genes[[3]]) # 61 flat

b_cluster_rna_list <- list()
for (i in 1:3) {
b_cluster_rna_list[[i]] <- data[which(cluster_obj[[3]]$em_cluster_assignment == i), ] %>% mutate("Cluster" = i)
}
saveRDS(b_cluster_rna_list, paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/biomarker/b_cluster_rna_list.rds"))

b_cluster_rna_df <- bind_rows(b_cluster_rna_list) %>% 
  rownames_to_column("Gene") %>% 
  dplyr::select(Gene, Cluster) %>%
  mutate(Cluster = ifelse(Cluster == 2, 1, Cluster)) %>%
  full_join(biomarker_rna_combined_df[, c("Gene", "Direction")]) %>%
  mutate(Direction_cluster = paste(Direction, Cluster, sep = "_"),
         Direction_cluster2 = ifelse(Direction_cluster == "Increased_1", "Resurfacing",
                                     ifelse(Direction_cluster == "Increased_3", "Increased", "Decreased"))) 
# unique(b_cluster_rna_df$Direction_cluster2)
```

### Cluster pathway analysis

```{r}
gene.df <- rna_corrected$genes %>% filter(SYMBOL %in% c(b_cluster_rna_df %>% filter(Direction_cluster2 == "Increased") %>% pull(Gene)))

  ego <- enrichGO(gene = gene.df$ENTREZID,
                  OrgDb         = org.Hs.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.2,
                  qvalueCutoff  = 0.2,
                  readable = TRUE)
  ego@result$log_adjpvalue <- abs(log10(ego@result$p.adjust))
  if (nrow(ego@result) > 0){
    if (length(unique(ego@result$geneID)) < nrow(ego@result)){
      ego@result <- aggregate(ego@result, by = list(ego@result$geneID), FUN = function(x) {
                                                                    if (is.numeric(x))
                                                                      cbind(x[1]) #max(x)
                                                                    else if (is.character(x))
                                                                      cbind(x[1])
                                                                    }) # keep first value only
    }
  }
  
  deseq_list$`group+months-increased`[["cluster_genes"]][["ego"]] <- ego
  
  ego@result$qvalue <- NA
  ego.simp <- clusterProfiler::simplify(ego, cutoff = 0.45, by="p.adjust")
  deseq_list$`group+months-increased`[["cluster_genes"]][["ego_simp"]] <- ego.simp
```

```{r}
gene.df <- rna_corrected$genes %>% filter(SYMBOL %in% c(b_cluster_rna_df %>% filter(Direction_cluster2 == "Resurfacing") %>% pull(Gene)))

  ego <- enrichGO(gene = gene.df$ENTREZID,
                  OrgDb         = org.Hs.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.2,
                  qvalueCutoff  = 0.2,
                  readable = TRUE)
  ego@result$log_adjpvalue <- abs(log10(ego@result$p.adjust))
  if (nrow(ego@result) > 0){
    if (length(unique(ego@result$geneID)) < nrow(ego@result)){
      ego@result <- aggregate(ego@result, by = list(ego@result$geneID), FUN = function(x) {
                                                                    if (is.numeric(x))
                                                                      cbind(x[1]) #max(x)
                                                                    else if (is.character(x))
                                                                      cbind(x[1])
                                                                    }) # keep first value only
    }
  }
  
  deseq_list$`group+months-resurfacing`[["cluster_genes"]][["ego"]] <- ego
  
  ego@result$qvalue <- NA
  ego.simp <- clusterProfiler::simplify(ego, cutoff = 0.45, by="p.adjust")
  deseq_list$`group+months-resurfacing`[["cluster_genes"]][["ego_simp"]] <- ego.simp
```


```{r}
# rm(ego, ego.simp, gene.df)
deseq_list$`group+months-resurfacing`$cluster_genes$ego_simp@result %>% arrange(p.adjust) %>% filter(p.adjust < 0.05, Count >= 2)
deseq_list$`group+months-increased`$cluster_genes$ego_simp@result %>% arrange(p.adjust) %>% filter(p.adjust < 0.05, Count >= 2)

#deseq_list$`group+months-increased` <- NULL
```

```{r}
e <- rbind(deseq_list$`group+months-resurfacing`$cluster_genes$ego@result %>% mutate("Direction_cluster" = "Resurfacing"),
               deseq_list$`group+months-increased`$cluster_genes$ego@result %>% mutate("Direction_cluster" = "Increased")) %>% 
  filter(p.adjust < 0.05) %>%
  group_by(Direction_cluster) %>%
  arrange(p.adjust)

e %>% filter(str_detect(Description, "T cell")) %>% pull(geneID) %>% str_split("/") %>% unlist() %>% unique() %>% sort()
e %>% filter(str_detect(Description, "chondr|bone|cartilage")) %>% pull(geneID) %>% str_split("/") %>% unlist() %>% unique() %>% sort()
e %>% filter(str_detect(Description, "chemotaxis|inflammatory|neutrophil|macroph|migration")) %>% pull(geneID) %>% str_split("/") %>% unlist() %>% unique() %>% sort()
e %>% filter(str_detect(Description, "vascular|angiogenesis|endothelial")) %>% pull(geneID) %>% str_split("/") %>% unlist() %>% unique() %>% sort()
```

```{r}
# Resurfacing
biomarker_rna_pathways <- rbind(
  deseq_list$`group+months-resurfacing`$cluster_genes$ego_simp@result %>% filter(p.adjust < 0.05) %>% slice_max(Count, n = 15) %>% arrange(p.adjust) %>%
    mutate(Cluster = "Resurfacing"), 
  
  deseq_list$`group+months-increased`$cluster_genes$ego_simp@result %>% filter(p.adjust < 0.05) %>% slice_max(Count, n = 5) %>% arrange(p.adjust) %>%
    mutate(Cluster = "Increased") ) %>%
  mutate(Value = "1",
         Description = str_to_sentence(Description),
         Description = gsub("transforming growth factor beta", "TGFb", Description),
         Description = gsub("gtpase", "GTPase", Description),
         Description = gsub("t cell", "T cell", Description),
         Description = gsub("Ras", "RAS", Description),
         Description = gsub("ii", "II", Description),
         Description = gsub("nf-kappab", "NF-kappaB", Description),
         Cluster = factor(Cluster, levels = c("Resurfacing", "Increased")))

p <- 
  
ggplot(biomarker_rna_pathways, aes(x = Value, y = reorder(Description, -log(p.adjust)))) +
  geom_point(aes(fill = -log(p.adjust), size = Count), shape = 21) +
  theme +
  theme(legend.position = "right", legend.justification = "left", legend.box = "vertical", legend.title = element_text(face = "bold")) +
    theme(axis.text.x = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_line(size = 0),
        strip.text = element_text(size = 5),
        ) +
  labs(title = paste("Pathways"),
       x = " ",
       y = " ",
       fill = "-Log(p-adj)",
       size = "DE genes") +
  scale_fill_gradient(low = "#150578", high = "#f78436") +
  facet_grid(Cluster~., space = "free", scales = "free") 

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/biomarker/biomarker-pathways.png"), p, width = 12, height = 14, units = 'cm', dpi = 600)
```


## Heatmap with intervals

```{r}
rna_combined_heat <- as.data.frame(deseq_list$`group+months`$GroupCLAD$heat_sig) 

m <- read.csv(paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/biomarker/biomarker-rna-heatmap.csv")) %>%
  mutate(Direction_cluster2 = factor(Direction_cluster2, levels = c("Decreased", "Resurfacing", "Increased")) ) %>%
  arrange(Direction_cluster2, Pathway)

rna_combined_heat_intervals <- rna_combined_heat %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  left_join(biomarker_rna_metadata[, c("Patient_days", "Months_grouped", "Group")]) %>%
  dplyr::select(!c("Patient_days")) %>%
  group_by(Group, Months_grouped) %>%
  summarise(across(where(is.numeric), mean)) %>%
  ungroup() %>%
  mutate(Group_month = paste(Group, Months_grouped, sep = "_")) %>%
  dplyr::select(!c("Group", "Months_grouped")) %>%
  column_to_rownames("Group_month") %>%
  t() %>%
  as.data.frame()

rna_combined_heat_intervals <- rna_combined_heat_intervals[m$Gene, ] 

df <- biomarker_rna_metadata[, c("Months_grouped", "Immunosuppression", "Group")] %>% 
  distinct() %>% 
  arrange(Group, Months_grouped) %>%
  mutate(Group_month = paste(Group, Months_grouped, sep = "_"),
         Group_month = factor(Group_month, levels = unique(Group_month))) %>%
  rename(`Time post-transplant (months)` = Months_grouped)
rownames(df) <- df$Group_month

identical(rownames(rna_combined_heat_intervals), m$Gene) # TRUE
identical(colnames(rna_combined_heat_intervals), rownames(df)) # TRUE
```

```{r}
# Annotation
text_list_big <- read.csv("tmixclust/biomarker/biomarker-rna-heatmap.csv") %>% filter(sc_heatmap_annotation == TRUE) %>% pull(Gene)

row_position <- rna_combined_heat_intervals %>% 
  rownames_to_column("Genes") %>% 
  mutate(Row = c(1:nrow(.))) %>% 
  dplyr::select(Genes, Row)

row_position_big <- row_position %>%
  filter(Genes %in% text_list_big)

text_annotation_big <- anno_mark(at = row_position_big %>% pull(Row) %>% as.numeric(), 
                                                   labels = row_position_big %>% pull(Genes), 
                                                   labels_gp = gpar(fontsize = 12, fontface = "bold"),
                                 which = "row")

text_annotation <- rowAnnotation(text_annotation_big = text_annotation_big)
```

```{r, fig.height=10, fig.width=8}
colHm <- colorRamp2(breaks = seq(-2.2, 2.2, length = 7), colors=c('#2166ac','#67a9cf','#d1e5f0', '#f7f7f7', '#fddbc7', '#ef8a62', '#CD0514'))
#max(as.matrix(rna_combined_heat_intervals))
p <- 
  
  draw(Heatmap(as.matrix(rna_combined_heat_intervals), 
        col = colHm,
        name = "z-score",
        column_title = "DE genes",
        column_title_gp = gpar(fontface = "bold"),
        row_title_gp = gpar(fontface = "bold"),
        row_names_gp = gpar(fontsize = 5),
        show_column_names = FALSE,
        show_row_names = FALSE,
        show_parent_dend_line = FALSE,
        cluster_row_slices = FALSE,
        cluster_rows = FALSE,
        show_row_dend = FALSE,
        top_annotation = annotate_heatmap(df, c("Immunosuppression", "Time post-transplant (months)", "Group")),
        #right_annotation = text_annotation,
        row_order = m$Gene,
        column_split = df$Group,
        column_order = levels(df$Group_month),
        row_split = m %>% pull(Direction_cluster2) ),
     padding = unit(c(0, 0, 0, 0), "cm"),
     merge_legend = TRUE,
     heatmap_legend_side = "left")

png(paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/biomarker/heat-cluster-direction.png"), width = 18, height = 25, units = "cm", res = 600)
p
invisible(dev.off())
```

```{r}
p2 <- 
  
  ggplot(m %>% mutate(Gene = factor(Gene, levels = unique(Gene))), aes(axis1 = Gene, axis2 = Pathway)) +
  scale_x_discrete(expand = c(.05, .05)) + 
  geom_alluvium(aes(fill = Pathway), fill = "grey60") +
  geom_stratum(size = 0.1, width = 0.2, alpha = 0.3) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 0) +
  theme_void() +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_blank())

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/tmixclust/rna/biomarker/alluvium.png"), p2, width = 4, height = 20, units = "cm", dpi = 600)
```
