---
title: "Biomarker cohort - Signature overlap and sensitivity analysis"
author: "Giulia Iacono"
output: html_document
date: Sys.Date()
---

# Signature overlap

```{r}
l <- list("Adaptive immunity (Stable)" = gene_cluster_assignment %>% filter(Cluster_description == "Adaptive immunity") %>% pull(Gene),
          "Innate immunity (Stable)" = gene_cluster_assignment %>% filter(Cluster_description == "Innate immunity") %>% pull(Gene),
          "Cell signalling (Stable)" = gene_cluster_assignment %>% filter(Cluster_description == "Cell signalling") %>% pull(Gene),
          "DE genes (Biomarker)" = biomarker_rna_combined_df$Gene )

l_p <- process_region_data(Venn(l))$item 
names(l_p) <- process_region_data(Venn(l))$name



p <- 
  ggVennDiagram(l, label_alpha = 0, label_size = 6, label = "count", set_size = 3, set_name_position = c(0.5, 1.5)) + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 1, face = "bold"), 
        legend.position = "none") +
  labs(title = "DE genes overlap across study cohorts") +
  scale_fill_gradient(low = "white", high = "lightgrey") +
  scale_x_continuous(expand = expansion(mult = c(0.4, 0.4))) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) 
ggsave("signature-overlap/de-genes-clusters-venn.png", p, width = 15, height = 13, units = 'cm', dpi = 500)  
```

```{r}
overlapping_genes <- c(l_p$`Innate immunity (Stable)/DE genes (Biomarker)`,
l_p$`Adaptive immunity (Stable)/DE genes (Biomarker)`,
l_p$`Cell signalling (Stable)/DE genes (Biomarker)`)
```


## Counts

```{r}
# Counts
b <- assay(deseq_list$`group+months`$vsd)[rownames(assay(deseq_list$`group+months`$vsd)) %in% c("SPHK1", "VEGFA", "S1PR1"),] %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(., var = "Patient_days") %>%
  pivot_longer(cols = -Patient_days, names_to = "Gene", values_to = "Expression") %>%
  left_join(biomarker_rna_metadata[, c("Patient_days", "Months", "Days", "Group", "Record.ID")]) %>%
  group_by(Record.ID) %>% 
  arrange(Days) %>% 
  mutate(Cohort = "Biomarker")

s <- assay(deseq_list$months$vsd)[rownames(assay(deseq_list$months$vsd)) %in% c("SPHK1", "VEGFA", "S1PR1"),] %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(., var = "Patient_days") %>%
  pivot_longer(cols = -Patient_days, names_to = "Gene", values_to = "Expression") %>%
  left_join(stable_rna_metadata[, c("Patient_days", "Months", "Days", "Group", "Record.ID")]) %>%
  group_by(Record.ID) %>% 
  arrange(Days) %>% 
  mutate(Cohort = "Stable")

#for (i in 1){ #length(unique(m$Gene))
  
  gene <- unique(b$Gene)[3]
  d1 <- b %>% filter(Gene == gene) 
  d2 <- s %>% filter(Gene == gene)
  
#p <-
  
ggplot() +
  geom_smooth(aes(x = Months, y = Expression, group = Group, colour = Group), method = "lm", formula = y ~ ns(x, 3), linewidth = 0.8, data = d1) + # biomarker
  geom_smooth(aes(x = Months, y = Expression, group = Group, colour = Group), method = "lm", formula = y ~ ns(x, 3), linewidth = 0.8, data = d2) + # stable
  theme +
  labs(x = "Months post-transplant", 
       y = "Log normalised expression", 
       title = as.character(gene)) +
  plot_colours(Group = TRUE) +
  plot_fill(Group = TRUE)

#}
```

## Heatmap with intervals

```{r}
# vsd <- vst(rna_corrected$counts, blind=FALSE)

d1 <- scale(t(as.data.frame( assay(vsd)[rownames(assay(vsd)) %in% biomarker_rna_combined, ] ))) %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  right_join(stable_rna_metadata[, c("Patient_days", "Months_grouped", "Group", "Record.ID")]) %>%
  filter(!Record.ID %in% biomarker_patients) %>% # remove CLAD-free patients that are also in biomarker cohort
  mutate(Cohort = "Stable") %>%
  dplyr::select(!c("Record.ID"))

d2 <- scale(t(as.data.frame( assay(vsd)[rownames(assay(vsd)) %in% biomarker_rna_combined, ] ))) %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  right_join(biomarker_rna_metadata[, c("Patient_days", "Months_grouped", "Group")]) %>%
  mutate(Cohort = "Biomarker") 

identical(colnames(d1), colnames(d2))

m1 <- rbind(d1, d2) %>%
  dplyr::select(!c("Patient_days")) %>%
  group_by(Cohort, Group, Months_grouped) %>%
  summarise(across(where(is.numeric), mean)) %>%
  ungroup() %>%
  arrange(desc(Cohort), Group, Months_grouped) %>%
  mutate(Cohort_group_month = paste(Cohort, paste(Group, Months_grouped, sep = "_"), sep = "_"),
         Cohort_group_month = factor(Cohort_group_month, levels = unique(Cohort_group_month))) %>%
  dplyr::select(!c("Cohort", "Group", "Months_grouped")) %>%
  column_to_rownames("Cohort_group_month") %>%
  t() %>%
  as.data.frame()

df <- biomarker_rna_metadata[, c("Months_grouped", "Immunosuppression", "Group")] %>% distinct() %>% mutate(Cohort = "Biomarker") %>%
  full_join(stable_rna_metadata[, c("Months_grouped", "Immunosuppression", "Group")] %>% distinct() %>% mutate(Cohort = "Stable") ) %>%
  arrange(desc(Cohort), Group, Months_grouped) %>%
  mutate(Cohort_group_month = paste(Cohort, paste(Group, Months_grouped, sep = "_"), sep = "_"),
         Cohort_group_month = factor(Cohort_group_month, levels = unique(Cohort_group_month)),
         Cohort = factor(Cohort, levels = c("Stable", "Biomarker"))) %>%
  rename(`Time post-transplant (months)` = Months_grouped)
rownames(df) <- df$Cohort_group_month

identical(colnames(m1), rownames(df))

colHm <- colorRamp2(breaks = seq(min(m1, na.rm = T)-0.5, max(m1, na.rm = T)-1, length = 7), colors=c('#2166ac','#67a9cf','#d1e5f0', '#f7f7f7', '#fddbc7', '#ef8a62', '#CD0514'))

d <- gene_cluster_assignment[, c("Gene", "Cluster_description")] %>% 
  mutate(Cluster_description = as.character(Cluster_description)) %>% 
  remove_rownames() %>%
  right_join(biomarker_rna_combined_df) %>%
  mutate(Cluster_description = ifelse(is.na(Cluster_description), "Unique", Cluster_description),
         Cluster_description = factor(Cluster_description, levels = c("Adaptive immunity", "Innate immunity", "Cell signalling", "Unique")))
```

```{r} 
p <- 
  
  draw(Heatmap(as.matrix(m1), 
        col = colHm,
        name = "z-score",
        column_title = "DE genes",
        column_title_gp = gpar(fontface = "bold"),
        show_column_names = FALSE,
        show_row_names = FALSE,
        row_names_gp = gpar(fontsize = 9),
        show_row_dend = FALSE,
        show_parent_dend_line = FALSE,
        cluster_row_slices = FALSE,
        cluster_rows = TRUE,
        top_annotation = annotate_heatmap(df, c("Cohort", "Time post-transplant (months)", "Group")),
        column_order = levels(df$Cohort_group_month),
        column_split = df$Cohort,
        row_split = d %>% pull(Cluster_description),
        row_title_gp = gpar(fontface = "bold")),
     padding = unit(c(0, 0, 2, 0), "cm"),
     merge_legend = TRUE,
     heatmap_legend_side = "left")

png("signature-overlap/rna-combined-heat-interval.png", width = 20, height = 30, units = "cm", res = 500)
p
invisible(dev.off())
```

## GO

```{r}
gene.df <- rna_corrected$genes %>% filter(SYMBOL %in% overlapping_genes) 

ego <- enrichGO(gene = gene.df$ENTREZID,
                  OrgDb         = org.Hs.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.2,
                  qvalueCutoff  = 0.2,
                  readable = TRUE)
ego@result$log_adjpvalue <- abs(log10(ego@result$p.adjust))
if (nrow(ego@result) > 0){
  if (length(unique(ego@result$geneID)) < nrow(ego@result)){
    ego@result <- aggregate(ego@result, by = list(ego@result$geneID), FUN = function(x) {
                                                                  if (is.numeric(x))
                                                                    cbind(x[1]) #max(x)
                                                                  else if (is.character(x))
                                                                  cbind(x[1])
                                                                  }) # keep first value only
  }
}

ego@result$qvalue <- NA
ego_simp <- clusterProfiler::simplify(ego, cutoff = 0.5, by="p.adjust")
ego_simp@result$log_adjpvalue <- abs(log10(ego_simp@result$p.adjust))

ego@result
ego_simp@result %>% filter(p.adjust < 0.05, Count > 4) %>% arrange(pvalue)
```

# DA molecules overlap

```{r}
l <- list("Glycerophospholipids\nmetabolism (Stable)" = stable_molecules_combined_df %>% filter(direction == "Increased") %>% pull(Molecule),
          "Amino acids and\ncarboxylic acid\nmetabolism (Stable)" = stable_molecules_combined_df %>% filter(direction == "Decreased") %>% pull(Molecule),
          "DE genes (Biomarker)" = biomarker_classes$Molecule )

p <- 
  ggVennDiagram(l, label_alpha = 0, label_size = 6, label = "count", set_size = 3, set_name_position = c(0.5, 1.5)) + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 1, face = "bold"), 
        legend.position = "none") +
  labs(title = "DA molecules overlap across study cohorts") +
  scale_fill_gradient(low = "white", high = "lightgrey") +
  scale_x_continuous(expand = expansion(mult = c(0.4, 0.4))) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) 

ggsave("signature-overlap/da-molecules-venn.png", p, width = 15, height = 13, units = 'cm', dpi = 500)  

l_p <- process_region_data(Venn(l))$item 
names(l_p) <- process_region_data(Venn(l))$name

l_p$`Decreased (Stable)/Increased in CLAD (Biomarker)`

length(overlapping_molecules) # 5 overlapping
```

## Heatmap with intervals

```{r}
d1 <- scale(t(as.data.frame( small_molecules[rownames(small_molecules) %in% biomarker_classes$Molecule, ] ))) %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  right_join(stable_small_molecules_metadata[, c("Patient_days", "Months_grouped", "Group", "Record.ID")]) %>%
  filter(!Record.ID %in% biomarker_patients) %>% # remove CLAD-free patients that are also in biomarker cohort
  mutate(Cohort = "Stable") %>%
  dplyr::select(!c("Record.ID"))

d2 <- scale(t(as.data.frame( small_molecules[rownames(small_molecules) %in% biomarker_classes$Molecule, ] ))) %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  right_join(biomarker_small_molecules_metadata[, c("Patient_days", "Months_grouped", "Group")]) %>%
  mutate(Cohort = "Biomarker") 

identical(colnames(d1), colnames(d2))

m2 <- rbind(d1, d2) %>%
  dplyr::select(!c("Patient_days")) %>%
  group_by(Cohort, Group, Months_grouped) %>%
  summarise(across(where(is.numeric), mean)) %>%
  ungroup() %>%
  arrange(desc(Cohort), Group, Months_grouped) %>%
  mutate(Cohort_group_month = paste(Cohort, paste(Group, Months_grouped, sep = "_"), sep = "_"),
         Cohort_group_month = factor(Cohort_group_month, levels = unique(Cohort_group_month))) %>%
  dplyr::select(!c("Cohort", "Group", "Months_grouped")) %>%
  column_to_rownames("Cohort_group_month") %>%
  t() %>%
  as.data.frame()

df <- biomarker_small_molecules_metadata[, c("Months_grouped", "Immunosuppression", "Group")] %>% distinct() %>% mutate(Cohort = "Biomarker") %>%
  full_join(stable_small_molecules_metadata[, c("Months_grouped", "Immunosuppression", "Group")] %>% distinct() %>% mutate(Cohort = "Stable") ) %>%
  arrange(desc(Cohort), Group, Months_grouped) %>%
  mutate(Cohort_group_month = paste(Cohort, paste(Group, Months_grouped, sep = "_"), sep = "_"),
         Cohort_group_month = factor(Cohort_group_month, levels = unique(Cohort_group_month)),
         Cohort = factor(Cohort, levels = c("Stable", "Biomarker"))) %>%
  rename(`Time post-transplant (months)` = Months_grouped)
rownames(df) <- df$Cohort_group_month

identical(colnames(m2), rownames(df))

colHm <- colorRamp2(breaks = seq(-2, 2, length = 7), colors=c('#2166ac','#67a9cf','#d1e5f0', '#f7f7f7', '#fddbc7', '#ef8a62', '#CD0514'))

d <- ms_cluster_assignment[, c("Molecule", "Cluster_description")] %>% 
  mutate(Cluster_description = as.character(Cluster_description)) %>% 
  remove_rownames() %>%
  right_join(biomarker_classes) %>%
  mutate(Cluster_description = ifelse(is.na(Cluster_description), "Unique", Cluster_description),
         Cluster_description = factor(Cluster_description, levels = c("Amino and carboxylic acid metabolism", "Glycerophospholipid metabolism", "Unique")))
```

```{r} 
p <- 
  
  draw(Heatmap(as.matrix(m2), 
        col = colHm,
        name = "z-score",
        column_title = "DA molecules",
        column_title_gp = gpar(fontface = "bold"),
        show_column_names = FALSE,
        show_row_names = FALSE,
        row_names_gp = gpar(fontsize = 6),
        show_row_dend = FALSE,
        show_parent_dend_line = FALSE,
        cluster_row_slices = FALSE,
        cluster_rows = TRUE,
        top_annotation = annotate_heatmap(df, c("Cohort", "Time post-transplant (months)", "Group")),
        column_order = levels(df$Cohort_group_month),
        column_split = df$Cohort,
        row_split = d %>% pull(Cluster_description),
        row_title_gp = gpar(fontface = "bold")),
     padding = unit(c(0, 0, 2, 0), "cm"),
     merge_legend = TRUE,
     heatmap_legend_side = "left")

png("signature-overlap/molecules-combined-heat-interval.png", width = 20, height = 30, units = "cm", res = 500)
p
invisible(dev.off())
```

# Combined heatmap

```{r}
identical(colnames(m1), colnames(m2))
m <- rbind(m2, m1)
d <- data.frame("Feature" = rownames(m)) %>%
  mutate("Dataset" = ifelse(Feature %in% rownames(m2), "Molecule", "Gene"))

colHm <- colorRamp2(breaks = seq(min(m, na.rm = T), max(m, na.rm = T)-1, length = 7), colors=c('#2166ac','#67a9cf','#d1e5f0', '#f7f7f7', '#fddbc7', '#ef8a62', '#CD0514'))

p <- 
  
  draw(Heatmap(as.matrix(m), 
        col = colHm,
        name = "z-score",
        column_title = "",
        column_title_gp = gpar(fontface = "bold"),
        show_column_names = FALSE,
        show_row_names = FALSE,
        row_names_gp = gpar(fontsize = 6),
        show_row_dend = FALSE,
        show_parent_dend_line = FALSE,
        cluster_row_slices = TRUE,
        cluster_rows = TRUE,
        top_annotation = annotate_heatmap(df, c("Cohort", "Time post-transplant (months)", "Group")),
        column_order = levels(df$Cohort_group_month),
        column_split = df$Cohort,
        row_split = d$Dataset,
        row_title_gp = gpar(fontface = "bold")),
     padding = unit(c(1, 0, 0, 0), "cm"),
     merge_legend = TRUE,
     heatmap_legend_side = "left")

png("signature-overlap/combined-heat-interval-all.png", width = 18, height = 20, units = "cm", res = 500)
p
invisible(dev.off())
```

# --------------------------------------
# Sensitivity analysis

Compare DE results for matched cohort against DE results for full cohort.

## RNA

```{r}
all_rna_metadata <- rna_corrected$samples %>% filter(Record.ID %in% unique(c(biomarker_patients, stable_patients)))
all_rna <- rna_corrected$counts[, all_rna_metadata$Patient_days]
identical(all_rna_metadata$Patient_days, colnames(all_rna)) #TRUE
dim(all_rna) # 12707 234
all_rna_metadata %>% group_by(Record.ID) %>% dplyr::count() # 47

all_rna_metadata %>% group_by(Group) %>% dplyr::count(Record.ID) %>% group_by(Group) %>% dplyr::count()
```

```{r}
# deseq_list$`group+months_full_cohort` <- NULL
test_variable <- "group+months_full_cohort"

m <- all_rna_metadata %>% filter(!is.na(GIT_ischemic_time))
d <- all_rna[, m$Patient_days]

de_matrix <- model.matrix(~Group + ns(Months, df = 3) + Transplant_indication + Total_ant_num + GIT_ischemic_time, m) 
deseq_list[[test_variable]][["design"]] <- "Group + ns(Months, df = 3) + Transplant_indication + Total_ant_num + GIT_ischemic_time"

# view(bind_rows(deseq_list$`group+months_full_cohort`$de_summary)) 
deseq_list$`group+months_full_cohort`$GroupCLAD$res_df %>% view()
```

```{r}
# Run
dds <- DESeqDataSetFromMatrix(countData = d,
                              colData = m,
                              design = de_matrix)  
dds <- DESeq(dds, minReplicatesForReplace = 3) 
mcols(dds)$maxCooks <- apply(assays(dds)[["cooks"]], 1, max) # add max cooks column
deseq_list[[test_variable]][["dds"]] <- dds

vsd <- vst(dds, blind=FALSE) 
deseq_list[[test_variable]][["vsd"]] <- vsd

# resultsNames(dds)

for (i in c(2)){ 
  
  name <- resultsNames(dds)[i]
  res <- lfcShrink(dds, coef = name, lfcThreshold = 0, type = "ashr", parallel = TRUE, BPPARAM = SnowParam(6) )
  deseq_list[[test_variable]][[name]][["res"]] <- res
  
  logFC_threshold <- 0
  
  c <- data.frame("maxCooks" = mcols(dds)$maxCooks, "Gene" = names(mcols(dds)$maxCooks))
    
  res.df <- as.data.frame(res) %>% 
    rownames_to_column("Gene") %>%
    left_join(c) %>%
    mutate(Direction = case_when(
        padj < 0.05 & log2FoldChange <= -logFC_threshold ~ "Decreased",
        padj < 0.05 & log2FoldChange >= logFC_threshold ~ "Increased",
        padj >= 0.05 | abs(log2FoldChange) < logFC_threshold ~ 'n.s.',
        is.na(padj) == TRUE | is.na(pvalue) == TRUE ~ "NA")) 
  deseq_list[[test_variable]][[name]][["res_df"]] <- res.df
  
  sig.results.df <- res.df %>% filter(padj < 0.05 & abs(log2FoldChange) >= logFC_threshold)  
  deseq_list[[test_variable]][[name]][["sig_results_df"]] <- sig.results.df
  deseq_list[[test_variable]][[name]][["heat_sig"]] <- t(scale(t(as.data.frame( assay(vsd)[rownames(assay(vsd)) %in% sig.results.df$Gene,]))))
  
  if (nrow(sig.results.df) == 0){
    next 
  }

  g <- sig.results.df %>% group_by(Direction) %>% mutate(Genes = paste0(Gene, collapse = ", ")) %>% dplyr::select(Direction, Genes) %>% distinct()
  
  deseq_list[[test_variable]][["de_summary"]][[name]] <- sig.results.df %>% 
    group_by(Direction) %>% 
    dplyr::count() %>% 
    ungroup() %>%    
    left_join(g, by = "Direction") %>%
    mutate(Name = name) 
  
  top.results.df <- res.df %>% filter(padj < 0.01 & abs(log2FoldChange) >= logFC_threshold) 
  deseq_list[[test_variable]][[name]][["top_results_df"]] <- top.results.df
   if (nrow(top.results.df) > 0){
      deseq_list[[test_variable]][[name]][["heat_top"]] <- t(scale(t(as.data.frame( assay(vsd)[rownames(assay(vsd)) %in% top.results.df$Gene,] )))) 
    }
}

saveRDS(deseq_list, "deseq_list_2026.rds")
```

```{r}
all_rna_combined_df <- deseq_list$`group+months_full_cohort`$GroupCLAD$sig_results_df %>%
  filter(abs(log2FoldChange) >= 1) #2317
all_rna_combined <- all_rna_combined_df$Gene
length(all_rna_combined) # 32

#25 overlapping when keeping logFC > 1

#1508 genes (adj-p < 0.05) were significant across both Matched and Full cohort analyses. 809 were unique to the Full cohort analysis. 901 were unique to the Matched cohort analysis. 

# supplementary table
suppl_rna_biomarker <- deseq_list$`group+months`$GroupCLAD$sig_results_df %>%
  dplyr::select(!Direction) %>%
  filter(abs(log2FoldChange) >= 1) 
colnames(suppl_rna_biomarker)[2:7] <- paste0(colnames(suppl_rna_biomarker)[2:7], "_biomarker")

suppl_full <- deseq_list$`group+months_full_cohort`$GroupCLAD$res_df %>% 
  dplyr::select(!Direction )
colnames(suppl_full)[2:7] <- paste0(colnames(suppl_full)[2:7], "_full")

suppl_rna_table <- suppl_rna_biomarker %>%
  left_join(suppl_full)

suppl_rna_table %>% filter(abs(log2FoldChange_biomarker) >= 1)
suppl_rna_table %>% filter(abs(log2FoldChange_full) >= 1, padj_full < 0.05) 
suppl_rna_table %>% filter(padj_full < 0.05) 

write.csv(suppl_rna_table, paste0(analysis_path, "transcriptomics-small-molecules/TableS2.csv"), row.names = FALSE)
```

### Venn diagrams

```{r}
l <- list("Matched cohort" = biomarker_rna_combined,
          "Full cohort" = all_rna_combined)

l_p <- process_region_data(Venn(l))$item 
names(l_p) <- process_region_data(Venn(l))$name

p <- 
  ggVennDiagram(l, label_alpha = 0, label_size = 6, label = "count", set_size = 3, set_name_position = c(0.5, 1.5)) + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 1, face = "bold"), 
        legend.position = "none") +
  labs(title = "DE genes overlap") +
  scale_fill_gradient(low = "white", high = "lightgrey") +
  scale_x_continuous(expand = expansion(mult = c(0.4, 0.4))) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) 

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/signature-overlap/de-genes-sensitivity-venn-top.png"), p, width = 15, height = 13, units = 'cm', dpi = 500)  
```

```{r}
l <- list("Matched" = deseq_list$`group+months`$GroupCLAD$sig_results_df$Gene,
          "Full" = deseq_list$`group+months_full_cohort`$GroupCLAD$sig_results_df$Gene)

l_p <- process_region_data(Venn(l))$item 
names(l_p) <- process_region_data(Venn(l))$name

p <- 
  ggVennDiagram(l, label_alpha = 0, label_size = 6, label = "count", set_size = 3, set_name_position = c(0.5, 1.5)) + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 1, face = "bold"), 
        legend.position = "none") +
  labs(title = "DE genes overlap") +
  scale_fill_gradient(low = "white", high = "lightgrey") +
  scale_x_continuous(expand = expansion(mult = c(0.4, 0.4))) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) 

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/signature-overlap/de-genes-sensitivity-venn.png"), p, width = 15, height = 13, units = 'cm', dpi = 500)  
```

### DE genes overlap

```{r}
df <- deseq_list$`group+months`$GroupCLAD$res_df %>% 
              dplyr::select(Gene, "log2FC_matched" = log2FoldChange, "padj_matched" = padj) %>%
      full_join(deseq_list$`group+months_full_cohort`$GroupCLAD$res_df %>% 
                  dplyr::select(Gene, "log2FC_full" = log2FoldChange, "padj_full" = padj)) %>%
  mutate(Significant = ifelse(Gene %in% l_p$Matched, "Matched analysis only", 
                         ifelse(Gene %in% l_p$`Matched/Full`, "Shared", 
                                ifelse(Gene %in% l_p$Full, "Full analysis only", "Both not significant")))) %>%
  mutate(Sig = ifelse(padj_matched < 0.05 & padj_full < 0.05, "Both sig", 
                      ifelse(padj_matched < 0.05 & padj_full >= 0.05, "Matched sig",
                             ifelse(padj_matched >= 0.05 & padj_full < 0.05, "Full sig", 
                                    ifelse(padj_matched >= 0.05 & padj_full >= 0.05, "Both ns", "na" )))))

p <- ggplot(df, aes(x = log2FC_matched, y = log2FC_full)) +
  geom_point(aes(colour = Significant)) +
  theme +
  labs(title = "Transcriptomics full vs matched cohort comparison") +
  scale_colour_manual(values = c("Matched analysis only" = "blue", "Both not significant" = "grey", "Shared" = "red", "Full analysis only" = "orange"))

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/signature-overlap/transcriptomics_sensitivity.png"), p, width = 15, height = 13, units = 'cm', dpi = 500)
```

### Plots

```{r}
# annotated on figure heatmap
#g <- c("ADAM8", "ADM", "CHST2", "CRISPLD2", "CSGALNACT1", "HAPLN3", "HS3ST3B1", "MMP7", "MMP9", "NAMPT", "PGGHG", "PHOSPHO1", "S1PR1", "SIGLEC12", "SPHK1", "STAB1","SULF2", "VEGFA", "ADORA2A", "BIRC3", "C3", "CSF3R", "CXCL2", "CXCR1", "CXCR2", "DUOX2", "DYSF", "FCAR", "FCN1", "HLA-DRB5", "MEFV", "NBEAL2", "NINJ1", "OSM", "PLA2G7", "PTGES", "RAI14", "RGS1", "S100P", "SELL", "VNN1", "GZMB", "IL2RA", "STAT4", "TNFRSF9", "TRAF3IP3", "TREML2", "AATK", "AMPD3", "ARAP3", "CDA", "CDC42EP2", "ELAPOR1", "KRT23", "H2BC4", "HAL", "HIVEP2", "IRAG1", "ITGA7", "LCN2", "LMNB1", "MEGF6", "MREG", "MUC13", "MUC4", "MUC5AC", "MXD1", "PIGR", "PITX1", "SLC37A3", "TESC", "TF" )

df <- deseq_list$`group+months_full_cohort`$GroupCLAD$res_df %>%
  mutate(Direction = case_when(
        padj < 0.05 & log2FoldChange <= -1 ~ "Decreased",
        padj < 0.05 & log2FoldChange >= 1 ~ "Increased",
        padj >= 0.05 | abs(log2FoldChange) < 1 ~ 'n.s.',
        is.na(padj) == TRUE | is.na(pvalue) == TRUE ~ "NA"),
        Font = ifelse(Gene %in% biomarker_rna_combined, "bold", "plain"),
        Biomarker = ifelse(Gene %in% biomarker_rna_combined, "Biomarker", "")
        ) 

# of those that are now significant above logFC > 1, the majority overlap with previous DE genes from matched cohort
p <- ggplot(df, aes(x = log2FoldChange, y = -log(padj))) +
  geom_point(colour = "grey") +
  geom_hline(yintercept = -log(0.05), lty = "dashed") +
  geom_vline(xintercept = c(-1, 1), lty = "dashed") +
  geom_text_repel(data = df %>% filter(Direction %in% c("Decreased", "Increased")), aes(label = Gene), color = "black", size = 2.5,
                  fontface = df %>% filter(Direction %in% c("Decreased", "Increased")) %>% pull(Font),
                  max.overlaps = Inf, segment.size = 0.2, nudge_y = 0.1) +
  theme +
  labs(title = "Full cohort analysis", x = "Log2FC", y = "-Log(padj)")

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/sensitivity/volcano.png"), p, width = 12, height = 10, units = 'cm', dpi = 500)  

# showing where all 222 DE genes from matched cohort are now, some padj is NA now
d <- df %>% filter(Biomarker == "Biomarker")
table(d$padj < 0.05) #12 171 still significant
table(is.na(d$padj)) #39 are now NA due to DESeq2 independent filtering

below_1 <- deseq_list$`group+months_full_cohort`$GroupCLAD$sig_results_df %>% filter(abs(log2FoldChange) < 1 & Gene %in% biomarker_rna_combined) %>% pull(Gene) %>% sort() #146
non_sig <- d %>% filter(is.na(padj)) %>% pull(Gene) %>% sort()

p <- ggplot(df %>% filter(Biomarker == "Biomarker"), aes(x = log2FoldChange, y = -log(padj))) +
  geom_point(colour = "grey") +
  geom_hline(yintercept = -log(0.05), lty = "dashed") +
  geom_vline(xintercept = c(-1, 1), lty = "dashed") +
  geom_text_repel(data = df %>% filter(Gene %in% below_1 & log2FoldChange < 0.9), aes(label = Gene), color = "black", size = 2.5, #direction = "x", hjust = 0,
                  max.overlaps = 35, segment.size = 0.2) +
  theme +
  labs(title = "Full cohort analysis (matched cohort DE genes only)", x = "Log2FC", y = "-Log(padj)")

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/sensitivity/volcano_matched_only.png"), p, width = 12, height = 10, units = 'cm', dpi = 500)  
```

### Pathways

```{r}
# pathways using DE genes with logFC > 1
gene.df <- rna_corrected$genes %>% filter(SYMBOL %in% all_rna_combined) 

  ego <- enrichGO(gene = gene.df$ENTREZID,
                  OrgDb         = org.Hs.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.2,
                  qvalueCutoff  = 0.2,
                  readable = TRUE)
  ego@result$log_adjpvalue <- abs(log10(ego@result$p.adjust))
  if (nrow(ego@result) > 0){
    if (length(unique(ego@result$geneID)) < nrow(ego@result)){
      ego@result <- aggregate(ego@result, by = list(ego@result$geneID), FUN = function(x) {
                                                                    if (is.numeric(x))
                                                                      cbind(x[1]) #max(x)
                                                                    else if (is.character(x))
                                                                      cbind(x[1])
                                                                    }) # keep first value only
    }
  }
  deseq_list$`group+months_full_cohort`[["cluster_genes"]][["ego"]] <- ego
  
  ego@result$qvalue <- NA
  ego.simp <- clusterProfiler::simplify(ego, cutoff = 0.35, by="p.adjust")
  deseq_list$`group+months_full_cohort`[["cluster_genes"]][["ego_simp"]] <- ego.simp

# rm(ego, ego.simp, gene.df)

deseq_list$`group+months_full_cohort`$cluster_genes$ego_simp@result %>% arrange(p.adjust) %>% filter(p.adjust < 0.05, Count > 2) 

all_rna_pathways <- deseq_list$`group+months_full_cohort`$cluster_genes$ego_simp@result %>% 
  arrange(p.adjust) %>% 
  filter(p.adjust < 0.05, Count > 2) %>%
  mutate(Description = str_to_sentence(Description))

p <- 
  
ggplot(all_rna_pathways, aes(x = 1, y = reorder(Description, -log(p.adjust)))) +
  geom_point(aes(fill = -log(p.adjust), size = Count), shape = 21) +
  theme +
  theme(legend.position = "right", legend.justification = "left", legend.box = "vertical", legend.title = element_text(face = "bold")) +
    theme(axis.text.x = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_line(size = 0)
        ) +
  labs(title = paste("Pathways"),
       x = " ",
       y = " ",
       fill = "-Log(p-adj)",
       size = "DE genes") +
  scale_fill_gradient(low = "#150578", high = "#f78436") 

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/sensitivity/all-pathways.png"), p, width =12, height = 9, units = 'cm', dpi = 500)  
```

```{r}
# Pathways using all DE genes with logFC < 1
g <- deseq_list$`group+months_full_cohort`$GroupCLAD$sig_results_df %>% filter(abs(log2FoldChange) < 1) %>% pull(Gene)

gene.df <- rna_corrected$genes %>% filter(SYMBOL %in% g) 

  ego <- enrichGO(gene = gene.df$ENTREZID,
                  OrgDb         = org.Hs.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.2,
                  qvalueCutoff  = 0.2,
                  readable = TRUE)
  ego@result$log_adjpvalue <- abs(log10(ego@result$p.adjust))
  if (nrow(ego@result) > 0){
    if (length(unique(ego@result$geneID)) < nrow(ego@result)){
      ego@result <- aggregate(ego@result, by = list(ego@result$geneID), FUN = function(x) {
                                                                    if (is.numeric(x))
                                                                      cbind(x[1]) #max(x)
                                                                    else if (is.character(x))
                                                                      cbind(x[1])
                                                                    }) # keep first value only
    }
  }
  deseq_list$`group+months_full_cohort`[["cluster_genes_2"]][["ego"]] <- ego
  
  ego@result$qvalue <- NA
  ego.simp <- clusterProfiler::simplify(ego, cutoff = 0.4, by="p.adjust")
  deseq_list$`group+months_full_cohort`[["cluster_genes_2"]][["ego_simp"]] <- ego.simp

# rm(ego, ego.simp, gene.df)

deseq_list$`group+months_full_cohort`$cluster_genes_2$ego_simp@result %>% arrange(p.adjust) %>% filter(p.adjust < 0.05) 
```


## Small molecules

```{r}
all_small_molecules_metadata <- small_molecules_metadata %>% filter(Record.ID %in% unique(c(biomarker_patients, stable_patients))) 
dim(all_small_molecules_metadata) #185 164
all_small_molecules <- small_molecules[, c(all_small_molecules_metadata$Patient_days)]
dim(all_small_molecules) #985 185

all_small_molecules_metadata %>% group_by(Record.ID) %>% dplyr::count() # 28

all_small_molecules_metadata %>% group_by(Group) %>% dplyr::count(Record.ID) %>% group_by(Group) %>% dplyr::count() # 10 vs 18
```

```{r}
design <- model.matrix(~Group + ns(Months, df = 3) + Transplant_indication + Total_ant_num + GIT_ischemic_time, all_small_molecules_metadata) 
dupcor <- duplicateCorrelation(all_small_molecules, design = design, block = all_small_molecules_metadata$Record.ID)
vfit <- lmFit(all_small_molecules, design, block = all_small_molecules_metadata$Record.ID, correlation = dupcor$consensus)
efit <- eBayes(vfit)
summary(decideTests(efit, p.value = 0.05, lfc = 0)) 

test_variable <- "group+months_full_cohort"
dir.create(paste0(analysis_path, 'transcriptomics-small-molecules/limma/', test_variable))
folder_id <- paste0(analysis_path, 'transcriptomics-small-molecules/limma/', test_variable, '/molecules/')
dir.create(folder_id)

molecules_list <- limma_molecules_process(list = molecules_list, 
                                    data = all_small_molecules, 
                                    metadata = all_small_molecules_metadata,
                                    coef_name = c("GroupCLAD"), 
                                    test_var1 = factor(c("Decreased", "Increased")), 
                                    title = test_variable, 
                                    efit = efit, 
                                    folder_id = folder_id, 
                                    logFC_threshold = 0)

all_molecules_combined <- molecules_list$`group+months_full_cohort`$GroupCLAD$sig_hits$Molecule
length(all_molecules_combined) # 6

molecules_list$`group+months_full_cohort`$GroupCLAD$sig_hits$Molecule

#"2-Hepteneoylglycine"     "DL-2-Aminooctanoic acid" "Galactosylhydroxylysine" "Creatine riboside"       "N-Heptanoylglycine"     "Hex3Cer 34:1;2O" 

molecules_list <- molecules_pathway_analysis(list = molecules_list, 
                                             data_info = small_molecules_info, 
                                             title = test_variable, 
                                             molecules = all_molecules_combined, 
                                             folder_id = folder_id, fella = fella.hsa)

saveRDS(molecules_list, paste0(analysis_path, "transcriptomics-small-molecules/limma/molecules_list.rds"))

# supplementary table
suppl_mol_biomarker <- molecules_list$`group+months`$GroupCLAD$sig_hits %>%
  left_join(biomarker_classes[, c("Molecule", "Rename")]) %>%
  dplyr::select(!c("direction", "Molecule"), "Molecule" = Rename ) %>%
  relocate(Molecule)
colnames(suppl_mol_biomarker)[2:7] <- paste0(colnames(suppl_mol_biomarker)[2:7], "_biomarker")

suppl_mol_full <- molecules_list$`group+months_full_cohort`$GroupCLAD$de_results %>%
  right_join(biomarker_classes[, c("Molecule", "Rename")]) %>%
  dplyr::select(!c("direction", "Molecule"), "Molecule" = Rename ) %>%
  relocate(Molecule)
colnames(suppl_mol_full)[2:7] <- paste0(colnames(suppl_mol_full)[2:7], "_full")

suppl_mol_table <- suppl_mol_biomarker %>%
  left_join(suppl_mol_full)

write.csv(suppl_mol_table, paste0(analysis_path, "transcriptomics-small-molecules/TableS3.csv"), row.names = FALSE)

suppl_mol_table %>% filter(adj.P.Val_biomarker < 0.05)
suppl_mol_table %>% filter(adj.P.Val_full < 0.2)
```

### Venn diagrams

```{r}
l <- list("Matched" = molecules_list$`group+months`$GroupCLAD$sig_hits$Molecule,
          "Full" = molecules_list$`group+months_full_cohort`$GroupCLAD$sig_hits$Molecule)

l_p <- process_region_data(Venn(l))$item 
names(l_p) <- process_region_data(Venn(l))$name

p <- 
  ggVennDiagram(l, label_alpha = 0, label_size = 6, label = "count", set_size = 3, set_name_position = c(0.5, 1.5)) + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 1, face = "bold"), 
        legend.position = "none") +
  labs(title = "DA molecules overlap") +
  scale_fill_gradient(low = "white", high = "lightgrey") +
  scale_x_continuous(expand = expansion(mult = c(0.4, 0.4))) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) 

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/signature-overlap/da-molecules-sensitivity-venn.png"), p, width = 15, height = 13, units = 'cm', dpi = 500)  
```

```{r}
# 0.05 threshold
df <- molecules_list$`group+months`$GroupCLAD$de_results %>% 
              dplyr::select(Molecule, "log2FC_matched" = logFC, "adj_pval_matched" = adj.P.Val) %>%
      full_join(molecules_list$`group+months_full_cohort`$GroupCLAD$de_results %>% 
              dplyr::select(Molecule, "log2FC_full" = logFC, "adj_pval_full" = adj.P.Val)) %>%
  mutate(Significant = ifelse(Molecule %in% l_p$Matched, "Matched analysis only", 
                         ifelse(Molecule %in% l_p$`Matched/Full`, "Shared", 
                                ifelse(Molecule %in% l_p$Full, "Full analysis only", "Both not significant")))) %>%
  mutate(Sig = ifelse(adj_pval_matched < 0.05 & adj_pval_full < 0.05, "Both sig", 
                      ifelse(adj_pval_matched < 0.05 & adj_pval_full >= 0.05, "Matched sig",
                             ifelse(adj_pval_matched >= 0.05 & adj_pval_full < 0.05, "Full sig", 
                                    ifelse(adj_pval_matched >= 0.05 & adj_pval_full >= 0.05, "Both ns", "na" )))))

p <- ggplot(df, aes(x = log2FC_matched, y = log2FC_full)) +
  geom_point(aes(colour = Significant)) +
  theme +
  labs(title = "Small molecules full vs matched cohort comparison") +
  scale_colour_manual(values = c("Matched analysis only" = "blue", "Both not significant" = "grey", "Shared" = "red"))

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/signature-overlap/da_molecules_sensitivity.png"), p, width = 15, height = 13, units = 'cm', dpi = 500)  
```

```{r}
# 0.2 threshold
l <- list("Matched (adj-p < 0.05)" = molecules_list$`group+months`$GroupCLAD$sig_hits$Molecule,
          "Full (adj-p < 0.2)" = molecules_list$`group+months_full_cohort`$GroupCLAD$de_results %>% filter(adj.P.Val < 0.2) %>% pull(Molecule))

l_p <- process_region_data(Venn(l))$item 
names(l_p) <- process_region_data(Venn(l))$name

ggVennDiagram(l, label_alpha = 0, label_size = 6, label = "count", set_size = 3, set_name_position = c(0.5, 1.5)) + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 1, face = "bold"), 
        legend.position = "none") +
  labs(title = "DA molecules overlap") +
  scale_fill_gradient(low = "white", high = "lightgrey") +
  scale_x_continuous(expand = expansion(mult = c(0.4, 0.4))) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1)))

l_p$`Matched (adj-p < 0.05)/Full (adj-p < 0.25)`
```

### Plots

```{r}
df <- molecules_list$`group+months_full_cohort`$GroupCLAD$de_results %>%
  mutate(Direction = case_when(
        adj.P.Val < 0.2 & logFC < 0 ~ "Decreased",
        adj.P.Val < 0.2 & logFC > 0 ~ "Increased",
        adj.P.Val >= 0.2 ~ 'n.s.',
        is.na(adj.P.Val) == TRUE | is.na(P.Value) == TRUE ~ "NA"),
        Font = ifelse(Molecule %in% biomarker_molecules_combined, "bold", "plain"),
        Biomarker = ifelse(Molecule %in% biomarker_molecules_combined, "Biomarker", "") ) %>%
  left_join(biomarker_classes[, c("Molecule", "Rename", "direction")] %>% dplyr::rename(direction_old = direction)) 

d <- df %>% filter(Biomarker == "Biomarker") 
table(d$adj.P.Val < 0.2) # 26

p <- ggplot(df, aes(x = logFC, y = -log(adj.P.Val))) +
  geom_point(colour = "grey") +
  geom_hline(yintercept = -log(0.05), lty = "dashed") +
  geom_text_repel(data = df %>% filter(direction %in% c("Decreased", "Increased")), aes(label = Molecule), color = "black", size = 2.5,
                  fontface = df %>% filter(direction %in% c("Decreased", "Increased")) %>% pull(Font),
                  max.overlaps = Inf, segment.size = 0.2, nudge_y = 0.1) +
  theme +
  labs(title = "Full cohort analysis", x = "Log2FC", y = "-Log(padj)")

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/sensitivity/volcano_molecules.png"), p, width = 12, height = 10, units = 'cm', dpi = 500)

# biomarker molecules only
p <- ggplot(d, aes(x = logFC, y = -log(adj.P.Val))) +
  geom_point(colour = "grey") +
  geom_hline(yintercept = -log(0.05), lty = "dashed") +
  geom_hline(yintercept = -log(0.2), lty = "dashed", colour = "grey") +
  theme +
  labs(title = "Full cohort analysis  (matched cohort DA molecules only)", x = "Log2FC", y = "-Log(padj)")

ggsave(paste0(analysis_path, "transcriptomics-small-molecules/sensitivity/volcano_molecules_only.png"), p, width = 12, height = 10, units = 'cm', dpi = 500)

d %>% filter(Direction %in% c("Decreased", "Increased")) %>% pull(Rename)
```



