---
title: "biomarker-molecules-associations"
author: "Giulia"
date: "09/05/2022"
output: html_document
---

# Molecules

```{r}
biomarker_small_molecules_metadata <- small_molecules_metadata %>% filter(Record.ID %in% biomarker_patients)
dim(biomarker_small_molecules_metadata) #153 163
biomarker_small_molecules <- small_molecules[, c(biomarker_small_molecules_metadata$Patient_days)]
dim(biomarker_small_molecules) #985 153

biomarker_small_molecules_metadata %>% group_by(Record.ID) %>% dplyr::count() # 23
```

# PCA

```{r}
# all
metadata <- biomarker_small_molecules_metadata
countdata <- biomarker_small_molecules
pca.list <- pca_process(countdata, metadata)

p <-
  
  ggplot(pca.list$data.PCA, aes(x = PC1, y = PC2)) +
  stat_ellipse(aes(group = Group, fill = Group, colour = Group), geom = 'polygon', type = 't', level = 0.95, alpha = 0.2) +
  geom_point(aes(fill = Group), shape = 21, size = 2) +
  theme +
  labs(title = 'Small molecules PCA',
       x = paste0('PC1 ', round(pca.list$varexp[1], 2), '%'),
       y = paste0('PC2 ', round(pca.list$varexp[2], 2), '%')) +
  plot_fill(Group = TRUE) +
  plot_colours(Group = TRUE)
  
ggsave("pca/biomarker-pca.pdf", p, width = 10, height = 6, units = 'cm')


# Time intervals
p <-
  
  ggplot(pca.list$data.PCA, aes(x = PC1, y = PC2)) +
  stat_ellipse(aes(group = Group, fill = Group, colour = Group), geom = 'polygon', type = 't', level = 0.95, alpha = 0.2) +
  geom_point(aes(fill = Group), shape = 21, size = 2) +
  theme +
  labs(title = 'Small molecules PCA',
       x = paste0('PC1 ', round(pca.list$varexp[1], 2), '%'),
       y = paste0('PC2 ', round(pca.list$varexp[2], 2), '%')) +
  plot_fill(Group = TRUE) +
  plot_colours(Group = TRUE) +
  facet_grid(.~Days_interval2) 
  
ggsave("pca/sm/pca-all-facet.pdf", p, width = 22, height = 6, units = 'cm')
```


```{r}
metadata <- clad_molecules_metadata
countdata <- clad_molecules

a <- data.frame(adonis2(formula = as.formula(paste('t(countdata) ~', "Group+Months+Transplant_indication+Record.ID")), 
                      data = metadata, 
                      distance = "eu", 
                      permutations = 999,
                      na.action = na.omit,
                      parallel = 6))

annotation <- paste(paste("SumOfSqs =", round(a["Group",]$SumOfSqs, 3)),
              paste("R2 =", round(a["Group",]$R2, 3)),
              paste("p =", round(a["Group",]$Pr..F., 3)), sep = " ; " )

pca.list <- pca_process(countdata, metadata)

p <-
  
  ggplot(pca.list$data.PCA, aes(x = PC1, y = PC2)) +
  stat_ellipse(aes(fill = Time_interval_combined, colour = Time_interval_combined), geom = 'polygon', type = 't', level = 0.95, alpha = 0.2) + 
  geom_point(aes(fill = Time_interval_combined, shape = Group), size = 2) +
  theme +
  annotate(geom = "text", x = -70, y = 30, label = annotation, size = 3, hjust = 0, vjust = 1) +
  labs(title = 'Small molecules PCA',
       shape = "Group",
       colour = "Time interval",
       fill = "Time interval",
       x = paste0('PC1 ', round(pca.list$varexp[1], 2), '%'),
       y = paste0('PC2 ', round(pca.list$varexp[2], 2), '%')) +
  scale_shape_manual(values = c(21, 24)) +
  plot_fill(Time_interval_combined = TRUE) +
  plot_colours(Time_interval_combined = TRUE)

ggsave("pca/sm/pca-interval.pdf", p, width = 12, height = 7, units = 'cm')
```


```{r}
permanova_list <- list()
p_list <- list()

metadata <- biomarker_small_molecules_metadata
countdata <- biomarker_small_molecules

for (i in c(1:2)){
  
      time <- unique(metadata$Days_interval2)[i]
      
      m <- metadata %>% filter(Days_interval2 == time)
      data <- countdata[, m$Patient_days]
      
      # adonis
      a <- data.frame(adonis2(formula = as.formula(paste('t(data) ~', "Group+Months+Transplant_indication+Total_ant_num+GIT_ischemic_time+Record.ID")), 
                      data = m, 
                      distance = "eu", 
                      permutations = 999,
                      na.action = na.omit,
                      parallel = 6))
  
      permanova_list[[i]] <- data.frame(a) %>% mutate(Test = time)
      
      annotation <- paste(paste("SumOfSqs =", round(permanova_list[[i]]["Group", ]$SumOfSqs, 3)),
              paste("R2 =", round(permanova_list[[i]]["Group", ]$R2, 3)),
              paste("p =", round(permanova_list[[i]]["Group", ]$Pr..F., 3)), sep = " ; " )
      
      # plot
      pca.list <- pca_process(data, m)

      p_list[[i]] <-
        
          ggplot(pca.list$data.PCA, aes(x = PC1, y = PC2)) +
            stat_ellipse(aes(fill = Group, colour = Group), geom = 'polygon', type = 't', level = 0.95, alpha = 0.2) + 
            geom_point(aes(fill = Group), shape = 21, size = 2) +
            theme +
            theme(plot.title = element_text(vjust = -2, size = 10)) +
            annotate(geom = "text", x = -50, y = 50, label = annotation, size = 3, hjust = 0, vjust = 1) +
            labs(title = time,
                 colour = "Group",
                 fill = "Group",
                 x = paste0('PC1 ', round(pca.list$varexp[1], 2), '%'),
                 y = paste0('PC2 ', round(pca.list$varexp[2], 2), '%')) +
                  plot_fill(Group = TRUE) +
                  plot_colours(Group = TRUE)
      
}

p <- ggarrange(p_list[[1]], p_list[[2]], ncol = 2, nrow = 1, common.legend = TRUE, legend = "bottom")
p <- annotate_figure(p, fig.lab = c("Molecules ordination"), fig.lab.face = "bold", fig.lab.size = 11)
ggsave("pca/biomarker-pca-groups.pdf", p, width = 14, height = 7, units = 'cm')

# No interactions betweeen groups and time, rather differences that are maintained over time from <3M up to >12M
```


# *Differential abundance Group+Months

```{r}
design <- model.matrix(~Group + ns(Months, df = 3) + Transplant_indication + Total_ant_num + GIT_ischemic_time, biomarker_small_molecules_metadata) 
dupcor <- duplicateCorrelation(biomarker_small_molecules, design = design, block = biomarker_small_molecules_metadata$Record.ID)
vfit <- lmFit(biomarker_small_molecules, design, block = biomarker_small_molecules_metadata$Record.ID, correlation = dupcor$consensus)
efit <- eBayes(vfit)
summary(decideTests(efit, p.value = 0.05, lfc = 0)) 
# topTreat(efit, coef = "GroupCLAD")

test_variable <- "group+months"
dir.create(paste0('limma/', test_variable))
folder_id <- paste0('limma/', test_variable, '/molecules/')
dir.create(folder_id)

molecules_list <- limma_molecules_process(list = molecules_list, 
                                    data = biomarker_small_molecules, 
                                    metadata = biomarker_small_molecules_metadata,
                                    coef_name = c("GroupCLAD"), 
                                    test_var1 = factor(c("Decreased", "Increased")), 
                                    title = test_variable, 
                                    efit = efit, 
                                    folder_id = folder_id, 
                                    logFC_threshold = 0)

biomarker_molecules_combined <- molecules_list$`group+months`$GroupCLAD$sig_hits$Molecule
length(biomarker_molecules_combined) # 64

molecules_list <- molecules_pathway_analysis(list = molecules_list, 
                                             data_info = small_molecules_info, 
                                             title = test_variable, 
                                             molecules = biomarker_molecules_combined, 
                                             folder_id = folder_id, fella = fella.hsa)

saveRDS(molecules_list, "limma/molecules_list.rds")

ms_classes <- read.csv("limma/group+months/molecules/biomarker-molecules-heatmap.csv") 
biomarker_classes <- molecules_list$`group+months`$GroupCLAD$sig_hits %>% 
  left_join(ms_classes[, c("Molecule", "Class", "Heatmap_annotation", "Rename")]) %>%
  as.data.frame() %>%
  arrange(direction, Class) %>%
  mutate(Class = factor(Class, levels = c(unique(Class)[-grep("Other", unique(Class))] , "Other") ))
rownames(biomarker_classes) <- biomarker_classes$Molecule
```

## Trajectories

```{r}
molecules_combined_heat <- as.data.frame(molecules_list$`group+months`$GroupCLAD$heat_sig_hits) 

data <- 
  molecules_combined_heat %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  left_join(biomarker_small_molecules_metadata[, c("Patient_days", "Months_grouped", "Group")]) %>%
  dplyr::select(!c("Patient_days")) %>%
  group_by(Group, Months_grouped) %>%
  summarise(across(where(is.numeric), mean)) %>%
  pivot_longer(-c("Months_grouped", "Group"), names_to = "Molecule", values_to = "Abundance") %>%
  mutate(Group_molecule = paste(Group, Molecule, sep = "_")) %>%
  left_join(molecules_list$`group+months`$GroupCLAD$sig_hits) %>%
  filter(Molecule %in% biomarker_molecules_combined)

# Lines
p <- 
  
  ggplot(data, aes(x = Months_grouped, y = Abundance)) +
  geom_smooth(aes(group = Group_molecule), method = "lm", formula = y ~ ns(x, 3), se = FALSE, colour = "lightgrey", linewidth = 0.3) +
  geom_smooth(aes(group = Group, colour = Group), method = "lm", formula = y ~ ns(x, 3), linewidth = 0.8) +
  labs(title = "Differentially abundant molecules\ntrajectory", x = "Time post-transplant (months)", y = "Scaled log abundance") +
  theme + 
  theme(legend.position = "bottom") +
  plot_colours(Group = TRUE) +
  scale_x_discrete(expand = c(0,0.3)) +
  facet_grid(direction~., switch = "y")

ggsave("limma/group+months/molecules/molecules-trajectories.pdf", p, width = 8.5, height = 12, units = 'cm')
```


#### Continuous

```{r}
data <- molecules_combined_heat %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  pivot_longer(!Patient_days, values_to = "Abundance", names_to = "Molecule") %>%
  left_join(biomarker_small_molecules_metadata[, c ("Patient_days", "Months", "Group")]) %>%
  mutate(Group_molecule = paste(Group, Molecule, sep = "_")) %>%
  left_join(molecules_list$`group+months`$GroupCLAD$sig_hits) %>%
  filter(Molecule %in% biomarker_molecules_combined)
  
p <- 
  
  ggplot(data, aes(x = Months, y = Abundance)) +
  geom_smooth(aes(group = Group_molecule), method = "lm", formula = y ~ ns(x, 3), se = FALSE, colour = "lightgrey", linewidth = 0.3) +
  geom_smooth(aes(group = Group, colour = Group), method = "lm", formula = y ~ ns(x, 3), linewidth = 0.8) +
  labs(title = "DA molecules trajectory", x = "Time post-transplant (months)", y = "Scaled log abundance") +
  theme + 
  theme(legend.position = "right") +
  plot_colours(Group = TRUE) +
  facet_grid(direction~., switch = "y")

ggsave("limma/group+months/molecules/molecules-trajectories-cont.pdf", p, width = 9, height = 10, units = 'cm')
```

## Heatmap

```{r}
molecules_combined_heat <- as.data.frame(molecules_list$`group+months`$GroupCLAD$heat_sig_hits) 

m <- biomarker_classes %>% filter(Heatmap_annotation == TRUE) 

ms_combined_heat_intervals <- molecules_combined_heat %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Patient_days") %>%
  left_join(biomarker_small_molecules_metadata[, c("Patient_days", "Months_grouped", "Group")]) %>%
  dplyr::select(!c("Patient_days")) %>%
  group_by(Group, Months_grouped) %>%
  summarise(across(where(is.numeric), mean)) %>%
  mutate(Group_months = paste(Group, Months_grouped, sep = "_")) %>%
  column_to_rownames("Group_months") %>%
  dplyr::select(!c("Group", "Months_grouped")) %>%
  t() %>%
  as.data.frame() 

ms_combined_heat_intervals <- ms_combined_heat_intervals[biomarker_classes$Molecule, ] 

df <- biomarker_small_molecules_metadata[, c("Months_grouped", "Immunosuppression", "Group")] %>% distinct() %>% arrange(Group, Months_grouped) %>%
  mutate(Group_months = paste(Group, Months_grouped, sep = "_"),
         Group_months = factor(Group_months, levels = unique(Group_months))) %>%
  rename(`Time post-transplant (months)` = Months_grouped)
rownames(df) <- df$Group_months

identical(rownames(ms_combined_heat_intervals), biomarker_classes$Molecule) # TRUE
identical(colnames(ms_combined_heat_intervals), rownames(df))

# Abbreviated molecules
rownames(ms_combined_heat_intervals) <- biomarker_classes$Rename

# Annotation
row_position <- ms_combined_heat_intervals %>% 
  rownames_to_column("Rename") %>% 
  mutate(Row = c(1:nrow(.))) %>% 
  dplyr::select(Rename, Row) %>%
  right_join(m) %>%
  left_join(data.frame(path_palette) %>% rownames_to_column("Class"))

color_vector <- setNames(row_position$path_palette, row_position$Rename)

text_annotation <- rowAnnotation(text_annotation_big = anno_mark(at = row_position %>% pull(Row) %>% as.numeric(), 
                                                   labels = row_position$Rename, 
                                                   labels_gp = gpar(fontsize = 12, fontface = "bold"), which = "row")#,
                                 #Class = anno_simple(x = row_position$Rename, pch = 16, pt_size = unit(1, "mm"), col = color_vector)
                                 )

class_annotation <- annotate_heatmap_row(metadata = biomarker_classes, 
                                        row_id = Rename, 
                                        row_or = biomarker_classes$Rename, 
                                        annotations = c("Class"), 
                                        path_palette = path_palette)

colHm <- colorRamp2(breaks = seq(min(ms_combined_heat_intervals, na.rm = T)-0.5, max(ms_combined_heat_intervals, na.rm = T), length = 7), colors=c('#2166ac','#67a9cf','#d1e5f0', '#f7f7f7', '#fddbc7', '#ef8a62', '#CD0514'))
```

```{r} 
h <-
  Heatmap(as.matrix(ms_combined_heat_intervals), 
        col = colHm,
        name = "z-score",
        column_title = "DA molecules",
        column_title_gp = gpar(fontface = "bold"),
        show_column_names = FALSE,
        show_row_names = FALSE,
        show_parent_dend_line = FALSE,
        cluster_row_slices = FALSE,
        cluster_rows = FALSE,
        top_annotation = annotate_heatmap(df, c("Immunosuppression", "Time post-transplant (months)", "Group")),
        column_order = levels(df$Group_months),
        row_split = biomarker_classes$direction,
        row_title_gp = gpar(fontface = "bold") )

h_list <- h + class_annotation + text_annotation 

p <-
  
  draw(h_list,
     merge_legend = TRUE, 
     heatmap_legend_side = "left")

png("limma/group+months/molecules/biomarker-heat-interval.png", width = 18, height = 25, units = "cm", res = 500)
p
invisible(dev.off())
```

```{r}
data <- molecules_combined_heat <- as.data.frame(molecules_list$`group+months`$GroupCLAD$heat_sig_hits) %>% filter(rownames(.) %in% biomarker_classes$Molecule)
identical(rownames(ms_combined_heat_intervals), biomarker_classes$Molecule) # TRUE
identical(colnames(ms_combined_heat_intervals), rownames(df))
#a <- a[rownames(biomarker_heat_classes), ]

p <- 
  
      draw(Heatmap(data, 
        name = "z-score",
        column_title = "Differentially expressed molecules",
        column_title_gp = gpar(fontface = "bold"),
        row_title = "Small molecules",  
        show_column_names = FALSE,
        show_row_names = TRUE,
        row_names_gp = gpar(fontsize = 6),
        column_order = colnames(data[, biomarker_small_molecules_metadata %>% arrange(Group, Days) %>% pull(Patient_days)]),
        top_annotation = annotate_heatmap(biomarker_small_molecules_metadata, c("Group", "Time_interval_detailed")), 
        #right_annotation = annotate_heatmap_row(metadata = clad_ms_heat_path, 
        #                                        row_id = Feature, 
        #                                        row_or = clad_ms_heat_path$Feature, 
        #                                        annotations = c("Class", "Significant"), 
        #                                        path_palette = c("#00AFB5", "#184E77","#7AE7C7", "#D81159")), #"#FF6700", 
        heatmap_legend_param = list(direction = "horizontal")),
        padding = unit(c(0, 0, 0, 0), "cm"),
     merge_legend = TRUE,
     heatmap_legend_side = "left")

pdf("limma/group+months/molecules/heat-sig.pdf", width = 14, height = 10)
p
invisible(dev.off()) 
```

### Class percentages

```{r}
p <- 
  
  biomarker_classes %>% 
  group_by(direction) %>%
  dplyr::count(Class) %>%
  arrange(n, .by_group = TRUE) %>%
  mutate(Class_per = n/sum(n),
         label_y = cumsum(0.5 * cumsum(Class_per))) %>%

  ggplot(aes(x = direction, y = Class_per, fill = Class)) +
  geom_bar(width = 0.9, stat = "identity", position = "fill") +
  #geom_text(aes(x = fct_rev(as.character(Cluster)), y = label_y, label = scales::percent(Pathway_per)), size = 2) +
  theme +
  theme(axis.text.y = element_text(size = 10)) +
  labs(title = "Class composition", x = "Direction in CLAD", y = "Percentage (%)") +
  #coord_flip() +
  scale_fill_manual(values = path_palette)

ggsave("limma/group+months/molecules/cluster-per.pdf", p, width = 15, height = 7, units = 'cm')
```

### Pathways

```{r}
# All together
d <- molecules_list$`group+months`$fella_output %>% filter(!Pathway_name %in% c("Leishmaniasis", "Systemic lupus erythematosus"), pvalue < 0.26) %>%
  mutate(Value = "1",
         Pathway_name = str_to_sentence(Pathway_name))
  
p <- 
  
ggplot(d, aes(x = Value, y = reorder(Pathway_name, -log(pvalue)))) +
  geom_point(aes(fill = -log(pvalue), size = CompoundHits), shape = 21) +
  theme +
  theme(legend.position = "right", legend.justification = "left", legend.box = "vertical") +
    theme(axis.text.x = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_line(size = 0),
        strip.text = element_text(size = 8),
        ) +
  labs(title = paste("Pathways"),
       x = " ",
       y = " ",
       fill = "-Log(p-adj)",
       size = "DA molecules") +
  scale_fill_gradient(low = "#150578", high = "#f78436")

ggsave("limma/group+months/molecules/pathways.pdf", p, width = 12, height = 3, units = 'cm')  
```


```{r}
# For each direction separately
biomarker_path_list <- list()

for (i in c(1)){ 
  
a <- c("Increased", "Decreased")[i]

compounds <- biomarker_classes %>% filter(direction == a) %>% pull(KEGG) %>% gsub(";.*", "", .) %>% na.omit()
path <- defineCompounds(compounds = compounds, data = fella.hsa)
path_analysis <- enrich(compounds = path@userinput@metabolites, data = fella.hsa, methods = listMethods(), approx = "normality")

path_analysis_table <- generateResultsTable(object = path_analysis, method = "hypergeom", data = fella.hsa)
colnames(path_analysis_table) <- c("Pathway", "Pathway_name", "CompoundHits", "CompoundsInPathway", "pvalue")

path_analysis_hy <- generateResultsGraph(object = path_analysis, method = "hypergeom", data = fella.hsa)
st.hy <- data.frame(get.edgelist(path_analysis_hy))
colnames(st.hy) <- c("name", "Pathway")
st.hy <- st.hy %>% inner_join(data.frame(vertex_attr(path_analysis_hy)), by = "name")

path_analysis_df <- st.hy %>%
  full_join(path_analysis_table, by = "Pathway") %>%
  na.omit() %>%
  dplyr::select("KEGG" = name, Pathway, "Metabolite" = label, Pathway_name, CompoundHits, CompoundsInPathway, pvalue)
path_analysis_df$Pathway_name <- gsub(" - Homo sapiens (human)", "", path_analysis_df$Pathway_name, fixed = TRUE)

biomarker_path_list[[a]] <- as.data.frame(path_analysis_df)

}

rm(compounds, path, path_analysis, path_analysis_table, path_analysis_hy, st.hy, path_analysis_df)
```

```{r}
d <- 
  
rbind(
biomarker_path_list$Decreased %>% filter(pvalue < 0.05, CompoundHits > 3) %>% arrange(pvalue) %>%
  filter(!Pathway_name %in% c("Mineral absorption", "ABC transporters", "Central carbon metabolism in cancer", "Aminoacyl-tRNA biosynthesis")) %>%
    mutate(Cluster = "Amino acids and carboxylic acids"),  # down

biomarker_path_list$Increased %>% 
  filter(pvalue < 0.05, CompoundHits > 3) %>% 
  arrange(pvalue) %>%
    mutate(Cluster = "Glycerophospholipids") %>% # up
  mutate(Value = "1") %>%
  mutate(Pathway_name = str_to_sentence(Pathway_name),
         Pathway_name = gsub("Camp", "cAMP", Pathway_name),
         Pathway_name = gsub("Ras", "RAS", Pathway_name))
         )
  
p <- 
  
ggplot(d, aes(x = Value, y = reorder(Pathway_name, -log(pvalue)))) +
  geom_point(aes(fill = -log(pvalue), size = CompoundHits), shape = 21) +
  theme +
  theme(legend.position = "right", legend.justification = "left", legend.box = "vertical") +
    theme(axis.text.x = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_line(size = 0),
        strip.text = element_text(size = 8),
        #axis.text.y = element_text(margin = margin(r = 100), hjust = 0)
        ) +
  labs(title = paste("Pathways"),
       x = " ",
       y = " ",
       fill = "-Log(p-adj)",
       size = "DA molecules") +
  scale_fill_gradient(low = "#150578", high = "#f78436") +
  facet_grid(Cluster~., space = "free", scales = "free")

ggsave("tmixclust/molecules/cluster-all-pathways.pdf", p, width = 14, height = 11, units = 'cm')  
```

### Counts

```{r}
ade <- molecules_list$`group+months`$GroupCLAD$sig_hits %>% filter(Molecule %in% c("6-O-(6-Deoxy-alpha-L-mannopyranosyl)-beta-D-glucopyranose", "Cer(d18:1/16:0)", "Creatine riboside", "HexCer 16:1;3O/26:0;(2OH)", "Lysylisoleucine"))
data <- as.matrix(biomarker_small_molecules)

for (i in 1:dim(ade)[1]){ 
  
selected_hit <- ade$Molecule[i] 
hit_interest <- data.frame("Intensity" = data[selected_hit,]) %>% # normalised data
  rownames_to_column(., var = "Patient_days") %>%
  right_join(biomarker_small_molecules_metadata[, c("Group", "Patient_days", "Months", "Record.ID")], by = "Patient_days") 

# Linear
mm_model_da_groups <- lmer(formula = as.formula(paste0("Intensity", ' ~ Group*ns(Months, df = 2) + (1|Record.ID)')), data = hit_interest)
mm_da_groups <- ggpredict(mm_model_da_groups, terms = c("Months [all]", "Group [all]"))
colnames(mm_da_groups)[1] <- "Months"


## Months
p <- 
  
  ggplot() + 
  geom_point(data = hit_interest, aes(x = Months, y = Intensity, fill = Group), shape = 21, size = 2) +
  theme +
  theme(legend.position = "none") +
  labs(title = paste(selected_hit),
       fill = "Group",
       colour = "Group",
       x = "Months post-transplant",
       y = "Log normalised intensity") +
  geom_ribbon(aes(x = Months, y = predicted, ymin = conf.low, ymax = conf.high, group = group), data = mm_da_groups, alpha = 0.2) +
  geom_line(aes(x = Months, y = predicted, group = group, colour = group), linewidth = 1, data = mm_da_groups) +
  plot_colours(Group = TRUE) +
  plot_fill(Group = TRUE) 

ggsave(paste0("limma/", test_variable, "/molecules/", paste0(gsub("/", "", selected_hit)), ".pdf"), p, width = 7, height = 6, units = 'cm')

}

hit_interest %>% arrange(Intensity)
```
